// SPDX-FileCopyrightText: 2025-2026 Jack Valinsky
// SPDX-License-Identifier: Unlicense OR CC0-1.0
#import "DashboardHTML.h"

NSString *ZukDashboardHTML(NSString *csrfNonce) {
    NSString *html = @"<!DOCTYPE html>\n"
    @"<html lang=\"en\">\n"
    @"<head>\n"
    @"<meta charset=\"utf-8\">\n"
    @"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    @"<title>Zuk Relay</title>\n"
    @"<meta name=\"csrf-nonce\" content=\"__CSRF_NONCE__\">\n"
    @"<style>\n"
    @":root{color-scheme:light dark;--bg:oklch(97% .004 15);"
    @"--surface:oklch(99% .003 15);--raised:oklch(93% .006 15);"
    @"--line:oklch(84% .008 15);--line-soft:oklch(90% .005 15);"
    @"--text:oklch(18% .01 15);--muted:oklch(43% .012 15);"
    @"--accent:oklch(52% .18 15);--accent-soft:oklch(94% .025 15);"
    @"--green:oklch(45% .15 145);--green-soft:oklch(94% .035 145);"
    @"--red:oklch(50% .2 25);--red-soft:oklch(94% .035 25);"
    @"--yellow:oklch(48% .13 70);--yellow-soft:oklch(94% .04 70);"
    @"--blue:oklch(48% .14 235);--blue-soft:oklch(94% .03 235);"
    @"--log:oklch(12% .005 200);--log-text:oklch(80% .01 200);"
    @"--log-muted:oklch(70% .005 200);--log-line:oklch(30% .014 15);--log-accent:oklch(60% .15 210);"
    @"--mono:ui-monospace,SFMono-Regular,\"SF Mono\",Menlo,Consolas,monospace}\n"
    @"@media(prefers-color-scheme:dark){:root{--bg:oklch(16% .008 15);"
    @"--surface:oklch(21% .011 15);--raised:oklch(27% .014 15);"
    @"--line:oklch(38% .012 15);--line-soft:oklch(31% .01 15);"
    @"--text:oklch(95% .004 15);--muted:oklch(72% .009 15);"
    @"--accent:oklch(68% .17 15);--accent-soft:oklch(27% .045 15);"
    @"--green:oklch(72% .16 145);--green-soft:oklch(27% .04 145);"
    @"--red:oklch(72% .18 25);--red-soft:oklch(27% .045 25);"
    @"--yellow:oklch(80% .14 70);--yellow-soft:oklch(28% .04 70);"
    @"--blue:oklch(75% .13 235);--blue-soft:oklch(27% .04 235)}}\n"
    @"*{box-sizing:border-box}\n"
    @"html{background:var(--bg)}body{margin:0;background:var(--bg);color:var(--text);"
    @"font-family:-apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif;"
    @"font-size:15px;line-height:1.5}\n"
    @"button,input,select{font:inherit}button,input,select,a{outline-offset:2px}"
    @"button:focus-visible,input:focus-visible,select:focus-visible,a:focus-visible{outline:2px solid var(--accent)}\n"
    @".shell{max-width:1440px;margin:0 auto;padding:24px}\n"
    @".topbar{display:flex;align-items:flex-start;justify-content:space-between;gap:24px;"
    @"padding-bottom:20px;border-bottom:1px solid var(--line)}\n"
    @".identity{display:flex;align-items:flex-start;gap:12px}.identity-mark{display:grid;place-items:center;"
    @"width:32px;height:32px;border-radius:8px;background:var(--accent);color:oklch(98% .002 15);"
    @"font-weight:700}.title{font-size:19px;line-height:1.2;margin:0 0 3px;font-weight:700}"
    @".subtitle{color:var(--muted);font-size:12px;margin:0}\n"
    @".live-state{display:flex;align-items:center;gap:10px;flex-wrap:wrap;justify-content:flex-end}"
    @".status-pill{display:inline-flex;align-items:center;gap:7px;padding:4px 9px;border-radius:50%;"
    @"background:var(--raised);color:var(--muted);font-size:12px;font-weight:650}"
    @".status-dot{width:8px;height:8px;border-radius:50%;background:currentColor;transition:color .2s}"
    @".status-pill.healthy{background:var(--green-soft);color:var(--green)}"
    @".status-pill.degraded{background:var(--yellow-soft);color:var(--yellow)}"
    @".status-pill.down{background:var(--red-soft);color:var(--red)}"
    @".updated{font-size:11px;color:var(--muted);font-variant-numeric:tabular-nums}\n"
    @"main{display:flex;flex-direction:column;gap:16px;padding-top:20px}"
    @".section-heading{display:flex;align-items:end;justify-content:space-between;gap:16px;margin-bottom:10px}"
    @".section-title{font-size:19px;line-height:1.2;margin:0;font-weight:700}"
    @".section-note{font-size:12px;color:var(--muted);margin:3px 0 0}"
    @".metric-strip{display:flex;flex-wrap:wrap;background:var(--surface);border:1px solid var(--line);"
    @"border-radius:8px;overflow:hidden}.metric{flex:1 1 150px;min-width:0;padding:12px 16px;"
    @"border-right:1px solid var(--line-soft)}.metric:last-child{border-right:0}"
    @".metric-label{display:block;color:var(--muted);font-size:11px;font-weight:650;margin-bottom:3px}"
    @".metric-value{display:block;font:650 18px/1.25 var(--mono);font-variant-numeric:tabular-nums}"
    @".metric-meta{display:block;color:var(--muted);font-size:11px;margin-top:2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}\n"
    @".signal-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}"
    @".panel{background:var(--surface);border:1px solid var(--line);border-radius:8px;overflow:hidden}"
    @".panel-head{display:flex;align-items:center;justify-content:space-between;gap:16px;"
    @"padding:12px 16px;border-bottom:1px solid var(--line-soft)}"
    @".panel-head h2,.panel-head h3{font-size:12px;line-height:1.2;margin:0;font-weight:700}"
    @".panel-body{padding:8px 16px}.stat{display:flex;justify-content:space-between;gap:16px;"
    @"padding:7px 0;border-bottom:1px solid var(--line-soft)}.stat:last-child{border-bottom:0}"
    @".stat-label{color:var(--muted)}.stat-value{font-family:var(--mono);font-weight:600;"
    @"font-variant-numeric:tabular-nums}.green{color:var(--green)}.red{color:var(--red)}.yellow{color:var(--yellow)}\n"
    @".upstream-tools{display:flex;align-items:center;gap:8px;flex-wrap:wrap}"
    @".field{height:30px;border:1px solid var(--line);border-radius:6px;background:var(--bg);"
    @"color:var(--text);padding:0 10px}.search{min-width:220px}.field::placeholder{color:var(--muted);opacity:1}\n"
    @".table-wrap{overflow-x:auto}.upstream-table{width:100%;border-collapse:collapse;font-size:12px}"
    @".upstream-table th{padding:8px 12px;background:var(--raised);color:var(--muted);"
    @"font-size:11px;font-weight:700;text-align:left;white-space:nowrap}"
    @".upstream-table td{padding:9px 12px;border-top:1px solid var(--line-soft);white-space:nowrap;"
    @"font-variant-numeric:tabular-nums}.upstream-table tbody tr:hover{background:var(--raised)}"
    @".upstream-table tbody tr.selected{background:var(--accent-soft)}"
    @".source-button{border:0;background:transparent;color:var(--text);font-weight:650;padding:0;"
    @"cursor:pointer;text-align:left}.source-button:hover{color:var(--accent);text-decoration:underline}"
    @".mono{font-family:var(--mono)}.dim{color:var(--muted)}.num{text-align:right!important}"
    @".badge{display:inline-flex;align-items:center;gap:5px;padding:2px 7px;border-radius:50%;"
    @"font-size:11px;font-weight:650;white-space:nowrap}.badge:before{content:'';width:6px;height:6px;"
    @"border-radius:50%;background:currentColor}.badge.connected,.badge.complete{background:var(--green-soft);color:var(--green)}"
    @".badge.connecting,.badge.requested,.badge.crawling{background:var(--yellow-soft);color:var(--yellow)}"
    @".badge.disconnected,.badge.failed{background:var(--red-soft);color:var(--red)}"
    @".badge.not-requested,.badge.unknown{background:var(--raised);color:var(--muted)}\n"
    @".empty{color:var(--muted);padding:18px 12px;text-align:center}.error-state{color:var(--red)}"
    @".inspector{display:grid;grid-template-columns:minmax(220px,.75fr) minmax(0,1.25fr);border-top:1px solid var(--line)}"
    @".inspector-summary{padding:16px;border-right:1px solid var(--line-soft)}"
    @".inspector-summary h3{font-size:15px;margin:0 0 4px}.inspector-url{color:var(--muted);font:11px/1.5 var(--mono);"
    @"overflow-wrap:anywhere}.inspector-badges{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}"
    @".detail-grid{display:grid;grid-template-columns:repeat(3,minmax(110px,1fr));padding:8px 16px}"
    @".detail{padding:8px 12px 8px 0}.detail dt{color:var(--muted);font-size:11px;margin-bottom:2px}"
    @".detail dd{margin:0;font-family:var(--mono);font-weight:600;overflow-wrap:anywhere}"
    @".kind-line{display:flex;flex-wrap:wrap;gap:6px;margin-top:12px}.kind{padding:2px 6px;"
    @"border-radius:4px;background:var(--raised);font:11px var(--mono);color:var(--muted)}\n"
    @".actions-content{display:grid;grid-template-columns:minmax(280px,1fr) auto;gap:16px;align-items:end;padding:12px 16px}"
    @".input-group{display:flex;gap:8px;align-items:end}.form-field{display:flex;flex:1;flex-direction:column;gap:4px}"
    @".form-field label{font-size:11px;font-weight:650;color:var(--muted)}"
    @"button{min-height:30px;border:1px solid var(--line);border-radius:6px;background:var(--surface);"
    @"color:var(--text);padding:5px 11px;font-size:12px;font-weight:650;cursor:pointer;transition:background .15s}"
    @"button:hover{background:var(--raised)}button.primary{border-color:var(--accent);background:var(--accent);"
    @"color:oklch(98% .002 15)}button.danger{border-color:var(--red);color:var(--red)}"
    @"button:disabled{cursor:not-allowed;opacity:.5}.btn-row{display:flex;gap:8px;flex-wrap:wrap}"
    @".action-status{padding:0 16px 12px;color:var(--muted);font-size:12px;min-height:18px}\n"
    @".event-feed{max-height:340px;overflow:auto;background:var(--log);color:var(--log-text);"
    @"font-family:var(--mono);font-size:11px;padding:4px 12px}.event{padding:6px 0;border-bottom:1px solid var(--log-line);"
    @"display:grid;grid-template-columns:72px 82px minmax(0,1fr);gap:8px}.event-time{color:var(--log-muted)}"
    @".event-type{color:var(--log-accent)}.event-detail{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}"
    @".event-feed .empty{color:var(--log-muted);text-align:left}\n"
    @".sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}\n"
    @"@media(max-width:800px){.shell{padding:16px}.signal-grid{grid-template-columns:1fr}"
    @".metric{flex-basis:33.333%}.inspector{grid-template-columns:1fr}.inspector-summary{border-right:0;"
    @"border-bottom:1px solid var(--line-soft)}.actions-content{grid-template-columns:1fr}.search{min-width:160px}}\n"
    @"@media(max-width:520px){.topbar{align-items:stretch;flex-direction:column}.live-state{justify-content:flex-start}"
    @".metric{flex-basis:50%;border-bottom:1px solid var(--line-soft)}.section-heading{align-items:flex-start;flex-direction:column}"
    @".upstream-tools{width:100%}.upstream-tools .field{flex:1;min-width:0}.detail-grid{grid-template-columns:repeat(2,1fr)}"
    @".input-group{align-items:stretch;flex-direction:column}.btn-row button{flex:1}.event{grid-template-columns:66px minmax(0,1fr)}"
    @".event-detail{grid-column:1/-1;white-space:normal}}\n"
    @"@media(prefers-reduced-motion:reduce){*,*:before,*:after{scroll-behavior:auto!important;transition-duration:.01ms!important}}\n"
    @"</style>\n"
    @"</head>\n"
    @"<body>\n<div class=\"shell\">\n"
    @"<header class=\"topbar\"><div class=\"identity\"><div class=\"identity-mark\" aria-hidden=\"true\">Ż</div>"
    @"<div><h1 class=\"title\">Zuk Relay</h1><p class=\"subtitle\">AT Protocol firehose operations</p></div></div>"
    @"<div class=\"live-state\"><span class=\"status-pill\" id=\"healthPill\">"
    @"<span class=\"status-dot\" aria-hidden=\"true\"></span><span id=\"healthText\">Checking telemetry…</span></span>"
    @"<time class=\"updated\" id=\"ts\" aria-live=\"polite\"></time><button type=\"button\" id=\"logoutButton\">Sign out</button></div></header>\n"
    @"<main>\n<section aria-labelledby=\"overviewTitle\"><div class=\"section-heading\"><div>"
    @"<h2 class=\"section-title\" id=\"overviewTitle\">Overall</h2>"
    @"<p class=\"section-note\">Current process totals and source availability</p></div></div>"
    @"<div class=\"metric-strip\">"
    @"<div class=\"metric\"><span class=\"metric-label\">Sources online</span><strong class=\"metric-value\" id=\"ovSources\">—</strong><span class=\"metric-meta\" id=\"ovSourcesMeta\">Loading</span></div>"
    @"<div class=\"metric\"><span class=\"metric-label\">Repositories discovered</span><strong class=\"metric-value\" id=\"ovRepos\">—</strong><span class=\"metric-meta\" id=\"ovReposMeta\">Across inventories</span></div>"
    @"<div class=\"metric\"><span class=\"metric-label\">Inbound events</span><strong class=\"metric-value\" id=\"ovEvents\">—</strong><span class=\"metric-meta\" id=\"ovRate\">Rate warming up</span></div>"
    @"<div class=\"metric\"><span class=\"metric-label\">Current sequence</span><strong class=\"metric-value\" id=\"ovSeq\">—</strong><span class=\"metric-meta\">Highest relay cursor</span></div>"
    @"<div class=\"metric\"><span class=\"metric-label\">Consumers</span><strong class=\"metric-value\" id=\"ovConsumers\">—</strong><span class=\"metric-meta\">Includes this dashboard</span></div>"
    @"</div></section>\n"
    @"<div class=\"signal-grid\">"
    @"<section class=\"panel\" aria-labelledby=\"flowTitle\"><div class=\"panel-head\"><h2 id=\"flowTitle\">Event flow</h2><span class=\"updated\">Since process start</span></div><div class=\"panel-body\">"
    @"<div class=\"stat\"><span class=\"stat-label\">Received</span><span class=\"stat-value\" id=\"flowReceived\">—</span></div>"
    @"<div class=\"stat\"><span class=\"stat-label\">Forwarded</span><span class=\"stat-value\" id=\"flowForwarded\">—</span></div>"
    @"<div class=\"stat\"><span class=\"stat-label\">Validation warnings</span><span class=\"stat-value yellow\" id=\"flowInvalid\">—</span></div>"
    @"<div class=\"stat\"><span class=\"stat-label\">Dropped</span><span class=\"stat-value red\" id=\"flowDropped\">—</span></div>"
    @"</div></section>"
    @"<section class=\"panel\" aria-labelledby=\"integrityTitle\"><div class=\"panel-head\"><h2 id=\"integrityTitle\">Repository integrity</h2><span class=\"updated\">Validation outcomes</span></div><div class=\"panel-body\">"
    @"<div class=\"stat\"><span class=\"stat-label\">MST checks</span><span class=\"stat-value\" id=\"integrityMst\">—</span></div>"
    @"<div class=\"stat\"><span class=\"stat-label\">Signature checks</span><span class=\"stat-value\" id=\"integritySig\">—</span></div>"
    @"<div class=\"stat\"><span class=\"stat-label\">Continuity verified</span><span class=\"stat-value green\" id=\"integrityContinuity\">—</span></div>"
    @"<div class=\"stat\"><span class=\"stat-label\">Sync resets / reconnects</span><span class=\"stat-value\" id=\"integrityRecovery\">—</span></div>"
    @"</div></section></div>\n"
    @"<section class=\"panel\" aria-labelledby=\"upstreamTitle\"><div class=\"panel-head\"><div>"
    @"<h2 id=\"upstreamTitle\">Upstream sources</h2><p class=\"section-note\" id=\"upstreamCount\">Loading source inventory</p></div>"
    @"<div class=\"upstream-tools\"><button type=\"button\" id=\"overallButton\" aria-pressed=\"true\">Overall</button>"
    @"<label class=\"sr-only\" for=\"statusFilter\">Filter by status</label><select class=\"field\" id=\"statusFilter\">"
    @"<option value=\"all\">All states</option><option value=\"attention\">Needs attention</option>"
    @"<option value=\"connected\">Connected</option><option value=\"disconnected\">Disconnected</option></select>"
    @"<label class=\"sr-only\" for=\"sourceSearch\">Search upstream sources</label>"
    @"<input class=\"field search\" id=\"sourceSearch\" type=\"search\" placeholder=\"Search hostname or URL\" autocomplete=\"off\"></div></div>"
    @"<div class=\"table-wrap\"><table class=\"upstream-table\"><thead><tr>"
    @"<th scope=\"col\">Source</th><th scope=\"col\">Connection</th><th scope=\"col\">Inventory</th>"
    @"<th scope=\"col\" class=\"num\">Repos</th><th scope=\"col\" class=\"num\">Events</th>"
    @"<th scope=\"col\" class=\"num\">Events/min</th><th scope=\"col\" class=\"num\">Cursor</th><th scope=\"col\">Last event</th>"
    @"</tr></thead><tbody id=\"upstreamRows\"><tr><td class=\"empty\" colspan=\"8\">Loading upstreams…</td></tr></tbody></table></div>"
    @"<div class=\"inspector\" id=\"inspector\"><div class=\"inspector-summary\"><h3 id=\"inspectorTitle\">Overall</h3>"
    @"<div class=\"inspector-url\" id=\"inspectorUrl\">All configured upstream sources</div><div class=\"inspector-badges\" id=\"inspectorBadges\"></div>"
    @"<div class=\"kind-line\" id=\"kindLine\"></div></div><dl class=\"detail-grid\">"
    @"<div class=\"detail\"><dt>Events</dt><dd id=\"iEvents\">—</dd></div><div class=\"detail\"><dt>Current rate</dt><dd id=\"iRate\">—</dd></div>"
    @"<div class=\"detail\"><dt>Repositories</dt><dd id=\"iRepos\">—</dd></div><div class=\"detail\"><dt>Cursor</dt><dd id=\"iCursor\">—</dd></div>"
    @"<div class=\"detail\"><dt>Last event</dt><dd id=\"iLast\">—</dd></div><div class=\"detail\"><dt>Connected for</dt><dd id=\"iConnected\">—</dd></div>"
    @"<div class=\"detail\"><dt>Reconnect attempts</dt><dd id=\"iRetries\">—</dd></div><div class=\"detail\"><dt>Crawl requested</dt><dd id=\"iRequested\">—</dd></div>"
    @"<div class=\"detail\"><dt>Inventory share</dt><dd id=\"iShare\">—</dd></div></dl></div></section>\n"
    @"<section class=\"panel\" aria-labelledby=\"actionsTitle\"><div class=\"panel-head\"><div><h2 id=\"actionsTitle\">Relay controls</h2>"
    @"<p class=\"section-note\">Changes are protected by your admin session</p></div></div><div class=\"actions-content\">"
    @"<form class=\"input-group\" id=\"crawlForm\"><div class=\"form-field\"><label for=\"hi\">PDS hostname</label>"
    @"<input class=\"field mono\" type=\"text\" id=\"hi\" placeholder=\"pds.example.com\" autocomplete=\"off\"></div>"
    @"<button class=\"primary\" type=\"submit\" id=\"crawlButton\">Request crawl</button></form><div class=\"btn-row\">"
    @"<button type=\"button\" id=\"rb\">Reconnect all</button><button type=\"button\" class=\"danger\" id=\"db\">Disconnect all</button></div></div>"
    @"<div class=\"action-status\" id=\"actionStatus\" aria-live=\"polite\"></div></section>\n"
    @"<section class=\"panel\" aria-labelledby=\"feedTitle\"><div class=\"panel-head\"><h2 id=\"feedTitle\">Live event feed</h2>"
    @"<span class=\"updated\" id=\"feedCount\">Connecting</span></div><div class=\"event-feed\" id=\"feed\" role=\"log\" aria-live=\"off\">"
    @"<div class=\"empty\">Connecting to the firehose…</div></div></section>\n"
    @"</main></div>\n<script>\n"
    @"const R=5000,F=new Intl.NumberFormat(),FC=new Intl.NumberFormat(undefined,{notation:'compact',maximumFractionDigits:1});"
    @"let ws=null,feedEvents=0;const S={health:null,metrics:null,upstreams:[],selected:'overall',filter:'all',query:'',"
    @"globalRate:null,rates:new Map(),previousMetrics:null,previousUpstreams:new Map(),sampledAt:0};\n"
    @"function t(i,v){const e=document.getElementById(i);if(e)e.textContent=v}\n"
    @"function n(v){return F.format(Number(v)||0)}function compact(v){return FC.format(Number(v)||0)}"
    @"function pct(a,b){return b>0?F.format(Math.round(a/b*100))+'%':'—'}"
    @"function age(v){if(!v)return'Never';const ms=Date.now()-new Date(v).getTime();if(!Number.isFinite(ms))return'Unknown';"
    @"const s=Math.max(0,Math.floor(ms/1000));if(s<10)return'Just now';if(s<60)return s+'s ago';"
    @"const m=Math.floor(s/60);if(m<60)return m+'m ago';const h=Math.floor(m/60);if(h<48)return h+'h ago';return Math.floor(h/24)+'d ago'}"
    @"function elapsed(v){if(!v)return'—';const s=Math.max(0,Math.floor((Date.now()-new Date(v).getTime())/1000));"
    @"if(s<60)return s+'s';const m=Math.floor(s/60);if(m<60)return m+'m';const h=Math.floor(m/60);return h+'h '+m%60+'m'}"
    @"function rateText(v){return v===null||!Number.isFinite(v)?'Warming up':(v===0?'0':v<.1?'<0.1':v.toFixed(v<10?1:0))+' / min'}"
    @"function stateName(v,allowed,fallback){return allowed.includes(v)?v:fallback}"
    @"function badge(label,state){const e=document.createElement('span');e.className='badge '+state;e.textContent=label;return e}"
    @"function td(row,value,className){const c=document.createElement('td');if(className)c.className=className;c.textContent=value;row.appendChild(c);return c}"
    @"function sum(key){return S.upstreams.reduce(function(total,p){return total+(Number(p[key])||0)},0)}"
    @"function combinedKinds(list){const out={};list.forEach(function(p){const kinds=p.eventCounts||{};Object.keys(kinds).forEach(function(k){out[k]=(out[k]||0)+(Number(kinds[k])||0)})});return out}"
    @"function renderKinds(kinds){const line=document.getElementById('kindLine');line.textContent='';const keys=Object.keys(kinds).filter(function(k){return kinds[k]>0}).sort();"
    @"if(!keys.length){const e=document.createElement('span');e.className='kind';e.textContent='No per-source events yet';line.appendChild(e);return}"
    @"keys.forEach(function(k){const e=document.createElement('span');e.className='kind';e.textContent=k+' '+n(kinds[k]);line.appendChild(e)})}"
    @"function csrfNonce(){return document.querySelector('meta[name=\"csrf-nonce\"]')?.content||''}"
    @"function refreshCSRF(response){const nonce=response.headers.get('X-UI-Admin-Nonce'),meta=document.querySelector('meta[name=\"csrf-nonce\"]');if(nonce&&meta)meta.content=nonce}"
    @"async function fj(url,options){const response=await fetch(url,options);refreshCSRF(response);if(response.status===401){location.replace('/login');throw Error('Session expired')}let body=null;try{body=await response.json()}catch(e){}"
    @"if(!response.ok)throw Error(body&&body.message?body.message:'Request failed ('+response.status+')');return body}\n"
    @"function sampleRates(metrics,upstreams){const now=Date.now();if(S.sampledAt){const minutes=(now-S.sampledAt)/60000;"
    @"if(minutes>0&&metrics&&S.previousMetrics)S.globalRate=Math.max(0,(Number(metrics.eventsReceived||0)-Number(S.previousMetrics.eventsReceived||0))/minutes);"
    @"upstreams.forEach(function(p){const prev=S.previousUpstreams.get(p.url);if(prev!==undefined)S.rates.set(p.url,Math.max(0,(Number(p.eventsReceived||0)-prev)/minutes))})}"
    @"S.previousMetrics=metrics?Object.assign({},metrics):S.previousMetrics;S.previousUpstreams=new Map(upstreams.map(function(p){return[p.url,Number(p.eventsReceived)||0]}));S.sampledAt=now}\n"
    @"function renderOverview(){const h=S.health||{},m=S.metrics||{},u=S.upstreams;const connected=u.filter(function(p){return p.connected}).length;"
    @"const ready=u.filter(function(p){return p.crawlState==='complete'}).length,repos=sum('crawlRepoCount');"
    @"const health=stateName(h.status,['healthy','degraded','down'],'degraded'),pill=document.getElementById('healthPill');"
    @"if(!u.length){pill.className='status-pill';t('healthText','Relay idle')}else if(!connected){pill.className='status-pill down';t('healthText','No sources online')}"
    @"else{pill.className='status-pill '+health;t('healthText',health==='healthy'?'Relay healthy':health==='degraded'?'Relay degraded':'Relay unavailable')}"
    @"t('ovSources',connected+' / '+u.length);t('ovSourcesMeta',ready+' inventories complete');t('ovRepos',compact(repos));"
    @"t('ovReposMeta',n(repos)+' exact');t('ovEvents',compact(m.eventsReceived));t('ovRate',rateText(S.globalRate));"
    @"t('ovSeq',n(m.currentSequence||h.currentSequence));t('ovConsumers',n(m.downstreamConnections||h.downstreamConnections));"
    @"t('flowReceived',n(m.eventsReceived));t('flowForwarded',n(m.eventsForwarded));t('flowInvalid',n(m.eventsInvalidated));t('flowDropped',n(m.eventsDropped));"
    @"t('integrityMst',n(m.mstValidationSuccess)+' ok / '+n(m.mstValidationFailure)+' failed');"
    @"t('integritySig',n(m.signatureValidationSuccess)+' ok / '+n(m.signatureValidationFailure)+' failed');"
    @"t('integrityContinuity',n(m.continuityVerified)+' ok / '+n(m.continuityFailures)+' failed');"
    @"t('integrityRecovery',n(m.syncResets)+' / '+n(m.reconnectionCount))}\n"
    @"function renderRows(){const body=document.getElementById('upstreamRows'),query=S.query.toLowerCase();body.textContent='';"
    @"const visible=S.upstreams.filter(function(p){const match=!query||String(p.hostname||'').toLowerCase().includes(query)||String(p.url||'').toLowerCase().includes(query);"
    @"const attention=!p.connected||['failed','requested','crawling'].includes(p.crawlState);const state=S.filter==='all'||(S.filter==='attention'&&attention)||"
    @"(S.filter==='connected'&&p.connected)||(S.filter==='disconnected'&&!p.connected);return match&&state}).sort(function(a,b){const aa=(!a.connected||a.crawlState==='failed')?0:1;"
    @"const bb=(!b.connected||b.crawlState==='failed')?0:1;return aa-bb||String(a.hostname).localeCompare(String(b.hostname))});"
    @"t('upstreamCount',visible.length===S.upstreams.length?n(S.upstreams.length)+' configured sources':n(visible.length)+' of '+n(S.upstreams.length)+' sources');"
    @"if(!visible.length){const row=document.createElement('tr'),message=S.upstreams.length?'No upstreams match this view':'No upstreams configured. Request a crawl below to add one.',cell=td(row,message,'empty');cell.colSpan=8;body.appendChild(row);return}"
    @"visible.forEach(function(p){const row=document.createElement('tr');if(S.selected===p.url)row.className='selected';"
    @"const source=document.createElement('td'),button=document.createElement('button');button.type='button';button.className='source-button';button.textContent=p.hostname||p.url;"
    @"button.title=p.url;button.setAttribute('aria-pressed',String(S.selected===p.url));button.onclick=function(){S.selected=p.url;renderRows();renderInspector()};source.appendChild(button);row.appendChild(source);"
    @"const connection=document.createElement('td'),connectionState=stateName(p.status,['connected','connecting','disconnected'],'unknown');"
    @"connection.appendChild(badge(connectionState,connectionState));row.appendChild(connection);const inventory=document.createElement('td'),crawl=stateName(p.crawlState,['requested','crawling','complete','failed','not-requested'],'not-requested');"
    @"inventory.appendChild(badge(crawl.replace('-', ' '),crawl));row.appendChild(inventory);td(row,n(p.crawlRepoCount),'num mono');td(row,n(p.eventsReceived),'num mono');"
    @"td(row,rateText(S.rates.has(p.url)?S.rates.get(p.url):null).replace(' / min',''),'num mono');td(row,Number(p.seq)>0?n(p.seq):'—','num mono');td(row,age(p.lastEventAt),'dim');body.appendChild(row)})}\n"
    @"function setInspectorBadges(items){const box=document.getElementById('inspectorBadges');box.textContent='';items.forEach(function(item){box.appendChild(badge(item[0],item[1]))})}"
    @"function setInspector(values){Object.keys(values).forEach(function(k){t(k,values[k])})}"
    @"function renderInspector(){const totalRepos=sum('crawlRepoCount'),overall=S.selected==='overall',p=S.upstreams.find(function(item){return item.url===S.selected});"
    @"document.getElementById('overallButton').setAttribute('aria-pressed',String(overall));if(!overall&&!p){S.selected='overall';return renderInspector()}"
    @"if(overall){const connected=S.upstreams.filter(function(item){return item.connected}).length,ready=S.upstreams.filter(function(item){return item.crawlState==='complete'}).length;"
    @"t('inspectorTitle','Overall');t('inspectorUrl','All configured upstream sources');const hasSources=S.upstreams.length>0;setInspectorBadges([[connected+' connected',!hasSources?'unknown':connected===S.upstreams.length?'connected':'connecting'],[ready+' inventories',!hasSources?'unknown':ready===S.upstreams.length?'complete':'requested']]);"
    @"setInspector({iEvents:n(sum('eventsReceived')),iRate:rateText(S.globalRate),iRepos:n(totalRepos),iCursor:n((S.metrics||{}).currentSequence),iLast:age(S.upstreams.reduce(function(latest,item){return !item.lastEventAt?latest:(!latest||new Date(item.lastEventAt)>new Date(latest)?item.lastEventAt:latest)},null)),"
    @"iConnected:hasSources?'Varies by source':'—',iRetries:n(sum('reconnectAttempts')),iRequested:n(S.upstreams.filter(function(item){return item.crawlRequested}).length)+' sources',iShare:totalRepos>0?'100%':'—'});renderKinds(combinedKinds(S.upstreams));return}"
    @"const status=stateName(p.status,['connected','connecting','disconnected'],'unknown'),crawl=stateName(p.crawlState,['requested','crawling','complete','failed','not-requested'],'not-requested');"
    @"t('inspectorTitle',p.hostname||p.url);t('inspectorUrl',p.url);setInspectorBadges([[status,status],[crawl.replace('-',' '),crawl]]);"
    @"setInspector({iEvents:n(p.eventsReceived),iRate:rateText(S.rates.has(p.url)?S.rates.get(p.url):null),iRepos:n(p.crawlRepoCount),iCursor:Number(p.seq)>0?n(p.seq):'—',"
    @"iLast:age(p.lastEventAt),iConnected:p.connected?elapsed(p.connectedAt):'Not connected',iRetries:n(p.reconnectAttempts),iRequested:p.crawlRequestedAt?age(p.crawlRequestedAt):'Not requested',"
    @"iShare:pct(Number(p.crawlRepoCount)||0,totalRepos)});renderKinds(p.eventCounts||{})}\n"
    @"async function poll(){const results=await Promise.allSettled([fj('/api/relay/health'),fj('/api/relay/metrics'),fj('/api/relay/upstreams')]);"
    @"if(results[0].status==='fulfilled')S.health=results[0].value;if(results[1].status==='fulfilled')S.metrics=results[1].value.metrics||{};"
    @"if(results[2].status==='fulfilled')S.upstreams=Array.isArray(results[2].value.upstreams)?results[2].value.upstreams:[];sampleRates(S.metrics,S.upstreams);"
    @"renderOverview();renderRows();renderInspector();const failed=results.filter(function(r){return r.status==='rejected'});"
    @"if(failed.length){const pill=document.getElementById('healthPill');pill.className='status-pill degraded';t('healthText','Telemetry delayed')}"
    @"const now=new Date();document.getElementById('ts').dateTime=now.toISOString();t('ts',(failed.length?'Partial update ':'Updated ')+now.toLocaleTimeString())}\n"
    @"document.getElementById('overallButton').addEventListener('click',function(){S.selected='overall';renderRows();renderInspector()});"
    @"document.getElementById('statusFilter').addEventListener('change',function(e){S.filter=e.target.value;renderRows()});"
    @"document.getElementById('sourceSearch').addEventListener('input',function(e){S.query=e.target.value.trim();renderRows()});"
    @"async function runAction(button,url,body,success){button.disabled=true;t('actionStatus','Working…');const headers={'Content-Type':'application/json','X-UI-Admin-Nonce':csrfNonce()};try{await fj(url,{method:'POST',credentials:'same-origin',headers:headers,body:JSON.stringify(body||{})});"
    @"t('actionStatus',success);setTimeout(poll,700);return true}catch(error){t('actionStatus',error.message||'Action failed');return false}finally{button.disabled=false}}"
    @"document.getElementById('crawlForm').addEventListener('submit',async function(e){e.preventDefault();const input=document.getElementById('hi'),host=input.value.trim();if(!host){t('actionStatus','Enter a PDS hostname first');return}"
    @"const button=document.getElementById('crawlButton');if(await runAction(button,'/api/relay/requestCrawl',{hostname:host},'Crawl requested for '+host))input.value=''});"
    @"document.getElementById('rb').addEventListener('click',function(e){runAction(e.currentTarget,'/api/relay/upstreams/reconnect-all',null,'Reconnect requested for all upstreams')});"
    @"document.getElementById('db').addEventListener('click',function(e){runAction(e.currentTarget,'/api/relay/upstreams/disconnect-all',null,'All upstreams disconnected')});\n"
    @"document.getElementById('logoutButton').addEventListener('click',async function(e){const button=e.currentTarget;button.disabled=true;try{const response=await fetch('/logout',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-UI-Admin-Nonce':csrfNonce()},body:'{}'});if(response.ok)location.replace('/login');else button.disabled=false}catch(error){button.disabled=false}});\n"
    @"const MAX_FRAME=10*1024*1024,MAX_DEPTH=64,MAX_ITEMS=10000;"
    @"function cborArg(b,o,a){if(a<24)return [a,o];"
    @"const n=a===24?1:a===25?2:a===26?4:a===27?8:0;"
    @"if(!n||o+n>b.length)throw Error('invalid CBOR length');let v=0;"
    @"for(let i=0;i<n;i++)v=v*256+b[o+i];"
    @"if(!Number.isSafeInteger(v))throw Error('CBOR number too large');return [v,o+n]}"
    @"function cborValue(b,o,d){if(o>=b.length)throw Error('truncated CBOR');"
    @"if(d>MAX_DEPTH)throw Error('CBOR nesting limit exceeded');"
    @"const h=b[o++],m=h>>5,a=h&31;let n,v,i,k,x;"
    @"if(m===0||m===1){[n,o]=cborArg(b,o,a);return[m===0?n:-1-n,o]}"
    @"if(m===2||m===3){[n,o]=cborArg(b,o,a);if(n>b.length-o)throw Error('truncated CBOR bytes');"
    @"x=m===2?b.slice(o,o+n):new TextDecoder().decode(b.slice(o,o+n));return[x,o+n]}"
    @"if(m===4){[n,o]=cborArg(b,o,a);if(n>MAX_ITEMS)throw Error('CBOR array limit exceeded');v=[];"
    @"for(i=0;i<n;i++){[x,o]=cborValue(b,o,d+1);v.push(x)}return[v,o]}"
    @"if(m===5){[n,o]=cborArg(b,o,a);if(n>MAX_ITEMS)throw Error('CBOR map limit exceeded');"
    @"v=Object.create(null);for(i=0;i<n;i++){[k,o]=cborValue(b,o,d+1);[x,o]=cborValue(b,o,d+1);"
    @"if(typeof k==='string')v[k]=x}return[v,o]}"
    @"if(m===6){[n,o]=cborArg(b,o,a);if(n!==42)throw Error('unsupported CBOR tag');return cborValue(b,o,d+1)}"
    @"if(m===7){if(a===20)return[false,o];if(a===21)return[true,o];if(a===22)return[null,o];"
    @"if(a===23)return[undefined,o];if(a===24){if(o>=b.length)throw Error('truncated simple value');return[b[o++],o]}"
    @"if(a===26){if(o+4>b.length)throw Error('truncated float');v=new DataView(b.buffer,b.byteOffset+o,4).getFloat32(0);return[v,o+4]}"
    @"if(a===27){if(o+8>b.length)throw Error('truncated float');v=new DataView(b.buffer,b.byteOffset+o,8).getFloat64(0);return[v,o+8]}"
    @"}throw Error('unsupported CBOR value')}"
    @"function cborFrame(data){let b=new Uint8Array(data),h,o;"
    @"if(b.length>MAX_FRAME)throw Error('firehose frame exceeds size limit');"
    @"[h,o]=cborValue(b,0,0);let body;[body,o]=cborValue(b,o,0);"
    @"if(o!==b.length||!h||typeof h!=='object'||Array.isArray(h)||h instanceof Uint8Array||"
    @"!body||typeof body!=='object'||Array.isArray(body)||body instanceof Uint8Array)"
    @"throw Error('invalid firehose frame maps');return{header:h,body:body,bytes:b.length}}"
    @"function feedText(v){if(v instanceof Uint8Array)return v.byteLength+' bytes';"
    @"if(v===null||v===undefined)return '';if(typeof v==='object')return JSON.stringify(v);return String(v)}"
    @"function feedSummary(frame){const h=frame.header,b=frame.body,tp=h.t||(h.op===-1?'error':'event');"
    @"let detail='seq='+(b.seq===undefined?'—':b.seq);"
    @"if(tp==='#commit'){const ops=Array.isArray(b.ops)?b.ops:[],a={},c={};"
    @"ops.forEach(function(op){const action=op&&op.action||'unknown',path=op&&op.path||'',col=path.split('/')[0]||'unknown';"
    @"a[action]=(a[action]||0)+1;c[col]=(c[col]||0)+1});"
    @"const actions=Object.keys(a).map(function(k){return k+':'+a[k]}).join(',')||'none';"
    @"const cols=Object.keys(c).slice(0,3).map(function(k){return k+':'+c[k]}).join(',');"
    @"detail='repo='+(b.repo||'unknown')+' · '+detail+' · ops='+ops.length+' ('+actions+')'+(cols?' · '+cols:'')}"
    @"else if(tp==='#identity')detail='did='+(b.did||'unknown')+' · '+detail+(b.handle?' · handle='+b.handle:'');"
    @"else if(tp==='#account')detail='did='+(b.did||'unknown')+' · '+detail+(b.active!==undefined?' · active='+b.active:'');"
    @"else if(tp==='#sync')detail='did='+(b.did||'unknown')+' · '+detail+(b.rev?' · rev='+b.rev:'');"
    @"else if(tp==='error')detail=(b.error||'error')+(b.message?' · '+b.message:'');"
    @"else detail=Object.keys(b).slice(0,4).map(function(k){return k+'='+feedText(b[k])}).join(' · ');"
    @"return{type:String(tp),detail:detail}}"
    @"function addFeedEvent(tp,dt){const f=document.getElementById('feed');feedEvents++;t('feedCount',n(feedEvents)+' received in this tab');"
    @"if(f.querySelector('.empty'))f.textContent='';const v=document.createElement('div');v.className='event';"
    @"const timeEl=document.createElement('span');timeEl.className='event-time';timeEl.textContent=new Date().toLocaleTimeString();"
    @"const typeEl=document.createElement('span');typeEl.className='event-type';typeEl.textContent=tp;"
    @"const detailEl=document.createElement('span');detailEl.className='event-detail';detailEl.textContent=dt;"
    @"v.appendChild(timeEl);v.appendChild(typeEl);v.appendChild(detailEl);f.insertBefore(v,f.firstChild);"
    @"while(f.children.length>200)f.removeChild(f.lastChild)}"
    @"async function feedMessage(data){try{const frame=cborFrame(await (data instanceof Blob?data.arrayBuffer():data));"
    @"const e=feedSummary(frame);addFeedEvent(e.type,e.detail)}catch(e){"
    @"addFeedEvent('binary',String(e.message||e))}}"
    @"function cw(){const p=location.protocol==='https:'?'wss:':'ws:';"
    @"ws=new WebSocket(p+'//'+location.host+'/xrpc/com.atproto.sync.subscribeRepos');ws.binaryType='arraybuffer';"
    @"ws.onopen=function(){document.getElementById('feed').innerHTML="
    @"'<div class=\"empty\">Listening for binary DAG-CBOR events…</div>';t('feedCount','Listening')};"
    @"ws.onmessage=function(ev){feedMessage(ev.data)};"
    @"ws.onerror=function(){t('feedCount','Connection error')};"
    @"ws.onclose=function(){document.getElementById('feed').innerHTML="
    @"'<div class=\"empty\">Disconnected. Reconnecting…</div>';t('feedCount','Reconnecting');setTimeout(cw,3000)}}\n"
    @"poll();setInterval(poll,R);cw();\n"
    @"</script>\n"
    @"</body>\n"
    @"</html>";
    return [html stringByReplacingOccurrencesOfString:@"__CSRF_NONCE__"
                                           withString:csrfNonce ?: @""];
}

NSString *ZukDashboardLoginHTML(NSString *csrfNonce) {
    NSString *html = @"<!DOCTYPE html>\n"
    @"<html lang=\"en\"><head><meta charset=\"utf-8\">"
    @"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
    @"<meta name=\"csrf-nonce\" content=\"__CSRF_NONCE__\">"
    @"<title>Sign in · Zuk Relay</title><style>"
    @":root{color-scheme:light dark;--bg:oklch(97% .004 15);--surface:oklch(99% .003 15);"
    @"--line:oklch(84% .008 15);--text:oklch(18% .01 15);--muted:oklch(43% .012 15);"
    @"--accent:oklch(52% .18 15);--red:oklch(50% .2 25)}"
    @"@media(prefers-color-scheme:dark){:root{--bg:oklch(16% .008 15);--surface:oklch(21% .011 15);"
    @"--line:oklch(38% .012 15);--text:oklch(95% .004 15);--muted:oklch(72% .009 15);"
    @"--accent:oklch(68% .17 15);--red:oklch(72% .18 25)}}"
    @"*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;padding:24px;"
    @"background:var(--bg);color:var(--text);font:15px/1.5 -apple-system,BlinkMacSystemFont,Roboto,Helvetica,Arial,sans-serif}"
    @"main{width:min(100%,360px);padding:24px;background:var(--surface);border:1px solid var(--line);border-radius:8px}"
    @".identity{display:flex;align-items:center;gap:12px;margin-bottom:24px}.mark{display:grid;place-items:center;width:32px;height:32px;"
    @"border-radius:8px;background:var(--accent);color:oklch(98% .002 15);font-weight:700}h1{font-size:19px;line-height:1.2;margin:0}"
    @"p{margin:3px 0 0;color:var(--muted);font-size:12px}form{display:flex;flex-direction:column;gap:12px}"
    @"label{font-size:12px;font-weight:650}input,button{min-height:38px;border:1px solid var(--line);border-radius:6px;font:inherit}"
    @"input{width:100%;padding:0 10px;background:var(--bg);color:var(--text)}input:focus-visible,button:focus-visible{outline:2px solid var(--accent);outline-offset:2px}"
    @"button{background:var(--accent);border-color:var(--accent);color:oklch(98% .002 15);font-weight:650;cursor:pointer}"
    @"button:disabled{opacity:.55;cursor:not-allowed}.error{min-height:20px;margin-top:12px;color:var(--red);font-size:12px}"
    @"</style></head><body><main><div class=\"identity\"><div class=\"mark\" aria-hidden=\"true\">Ż</div>"
    @"<div><h1>Zuk Relay</h1><p>Sign in to relay operations</p></div></div>"
    @"<form id=\"loginForm\"><label for=\"password\">Relay admin password</label>"
    @"<input id=\"password\" type=\"password\" autocomplete=\"current-password\" required autofocus>"
    @"<button id=\"submitButton\" type=\"submit\">Sign in</button></form>"
    @"<div class=\"error\" id=\"error\" role=\"alert\" aria-live=\"polite\"></div></main>"
    @"<script>const form=document.getElementById('loginForm'),button=document.getElementById('submitButton'),error=document.getElementById('error');"
    @"form.addEventListener('submit',async function(event){event.preventDefault();button.disabled=true;error.textContent='';"
    @"const nonce=document.querySelector('meta[name=\"csrf-nonce\"]').content;try{const response=await fetch('/login',{method:'POST',credentials:'same-origin',"
    @"headers:{'Content-Type':'application/json','X-UI-Admin-Nonce':nonce},body:JSON.stringify({password:document.getElementById('password').value})});"
    @"const nextNonce=response.headers.get('X-UI-Admin-Nonce');if(nextNonce)document.querySelector('meta[name=\"csrf-nonce\"]').content=nextNonce;"
    @"if(response.status===403){location.reload();return}if(!response.ok){error.textContent=response.status===401?'Incorrect password':'Unable to sign in';return}location.replace('/')}"
    @"catch(e){error.textContent='Unable to reach the relay'}finally{button.disabled=false}});</script></body></html>";
    return [html stringByReplacingOccurrencesOfString:@"__CSRF_NONCE__"
                                           withString:csrfNonce ?: @""];
}
