// SPDX-FileCopyrightText: 2025-2026 Jack Valinsky
// SPDX-License-Identifier: Unlicense OR CC0-1.0
#import "DashboardHTML.h"

NSString *ZukDashboardHTML(void) {
    return @"<!DOCTYPE html>\n"
    @"<html lang=\"en\">\n"
    @"<head>\n"
    @"<meta charset=\"utf-8\">\n"
    @"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    @"<title>Zuk Relay</title>\n"
    @"<style>\n"
    @":root{--bg:#0d1117;--card:#161b22;--border:#30363d;--text:#c9d1d9;--dim:#8b949e;"
    @"--accent:#58a6ff;--green:#3fb950;--red:#f85149;--yellow:#d29922;"
    @"--mono:ui-monospace,SFMono-Regular,\"SF Mono\",Menlo,Consolas,monospace}\n"
    @"*{margin:0;padding:0;box-sizing:border-box}\n"
    @"body{background:var(--bg);color:var(--text);font-family:-apple-system,"
    @"BlinkMacSystemFont,\"Segoe UI\",Helvetica,Arial,sans-serif;font-size:14px;"
    @"line-height:1.5;padding:24px;max-width:1200px;margin:0 auto}\n"
    @".header{display:flex;align-items:center;justify-content:space-between;"
    @"margin-bottom:24px}\n"
    @".header h1{font-size:20px;font-weight:600;display:flex;align-items:center;gap:10px}\n"
    @".status-dot{width:10px;height:10px;border-radius:50%;background:var(--dim);"
    @"transition:background .3s}\n"
    @".status-dot.healthy{background:var(--green)}\n"
    @".status-dot.degraded{background:var(--yellow)}\n"
    @".status-dot.down{background:var(--red)}\n"
    @".grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));"
    @"gap:16px;margin-bottom:16px}\n"
    @".card{background:var(--card);border:1px solid var(--border);border-radius:8px;"
    @"padding:16px}\n"
    @".card h2{font-size:12px;font-weight:600;text-transform:uppercase;"
    @"letter-spacing:.5px;color:var(--dim);margin-bottom:12px}\n"
    @".stat{display:flex;justify-content:space-between;padding:6px 0;"
    @"border-bottom:1px solid var(--border)}\n"
    @".stat:last-child{border-bottom:none}\n"
    @".stat-label{color:var(--dim)}\n"
    @".stat-value{font-family:var(--mono);font-weight:600}\n"
    @".stat-value.green{color:var(--green)}.stat-value.red{color:var(--red)}\n"
    @".upstream-list{list-style:none;display:flex;flex-direction:column;gap:6px}\n"
    @".upstream-item{display:grid;grid-template-columns:minmax(180px,1.5fr) minmax(120px,1fr)"
    @"auto auto;align-items:center;gap:12px;padding:10px 12px;"
    @"background:rgba(255,255,255,.03);border-radius:6px;font-size:12px}\n"
    @".upstream-host{font-weight:600;color:var(--text)}\n"
    @".upstream-url{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"
    @"font-family:var(--mono);font-size:11px;color:var(--dim)}\n"
    @".crawl-meta{color:var(--dim);font-size:11px;white-space:nowrap}\n"
    @".badge{padding:2px 8px;border-radius:12px;font-size:11px;font-weight:600;"
    @"text-transform:uppercase;white-space:nowrap}\n"
    @".badge.connected,.badge.complete{background:rgba(63,185,80,.15);color:var(--green)}\n"
    @".badge.connecting,.badge.requested,.badge.crawling{background:rgba(210,153,34,.15);color:var(--yellow)}\n"
    @".badge.disconnected,.badge.failed{background:rgba(248,81,73,.15);color:var(--red)}\n"
    @".badge.not-requested{background:rgba(139,148,158,.15);color:var(--dim)}\n"
    @".server-status{font-size:11px;color:var(--dim);white-space:nowrap}\n"
    @".actions{display:flex;flex-direction:column;gap:12px}\n"
    @".input-group{display:flex;gap:8px}\n"
    @"input[type=text]{flex:1;background:rgba(255,255,255,.05);border:1px solid var(--border);"
    @"border-radius:6px;padding:8px 12px;color:var(--text);font-family:var(--mono);"
    @"font-size:13px;outline:none}\n"
    @"input[type=text]:focus{border-color:var(--accent)}\n"
    @"button{background:rgba(88,166,255,.1);border:1px solid rgba(88,166,255,.3);"
    @"border-radius:6px;padding:8px 16px;color:var(--accent);font-size:13px;"
    @"font-weight:500;cursor:pointer;transition:background .15s}\n"
    @"button:hover{background:rgba(88,166,255,.2)}\n"
    @"button.danger{background:rgba(248,81,73,.1);border-color:rgba(248,81,73,.3);"
    @"color:var(--red)}\n"
    @"button.danger:hover{background:rgba(248,81,73,.2)}\n"
    @".btn-row{display:flex;gap:8px}\n"
    @".event-feed{max-height:300px;overflow-y:auto;font-family:var(--mono);font-size:12px}\n"
    @".event{padding:4px 0;border-bottom:1px solid var(--border);display:flex;gap:8px}\n"
    @".event-time{color:var(--dim);min-width:70px}\n"
    @".event-type{color:var(--accent);min-width:80px}\n"
    @".event-detail{color:var(--text);flex:1;overflow:hidden;text-overflow:ellipsis;"
    @"white-space:nowrap}\n"
    @".empty{color:var(--dim);font-style:italic;padding:8px 0}\n"
    @".updated{font-size:11px;color:var(--dim)}\n"
    @"</style>\n"
    @"</head>\n"
    @"<body>\n"
    @"<div class=\"header\"><h1><span class=\"status-dot\" id=\"sd\"></span> Zuk Relay</h1>"
    @"<span class=\"updated\" id=\"ts\"></span></div>\n"
    @"<div class=\"grid\">\n"
    @"<div class=\"card\"><h2>Health</h2>"
    @"<div class=\"stat\"><span class=\"stat-label\">Status</span>"
    @"<span class=\"stat-value\" id=\"hs\">—</span></div>"
    @"<div class=\"stat\"><span class=\"stat-label\">Upstreams</span>"
    @"<span class=\"stat-value\" id=\"uc\">—</span></div>"
    @"<div class=\"stat\"><span class=\"stat-label\">Downstreams</span>"
    @"<span class=\"stat-value\" id=\"dc\">—</span></div>"
    @"<div class=\"stat\"><span class=\"stat-label\">Sequence</span>"
    @"<span class=\"stat-value\" id=\"cs\">—</span></div></div>\n"
    @"<div class=\"card\"><h2>Events</h2>"
    @"<div class=\"stat\"><span class=\"stat-label\">Received</span>"
    @"<span class=\"stat-value\" id=\"er\">—</span></div>"
    @"<div class=\"stat\"><span class=\"stat-label\">Validated</span>"
    @"<span class=\"stat-value\" id=\"ev\">—</span></div>"
    @"<div class=\"stat\"><span class=\"stat-label\">Forwarded</span>"
    @"<span class=\"stat-value\" id=\"ef\">—</span></div>"
    @"<div class=\"stat\"><span class=\"stat-label\">Dropped</span>"
    @"<span class=\"stat-value\" id=\"ed\">—</span></div></div>\n"
    @"<div class=\"card\"><h2>Validation</h2>"
    @"<div class=\"stat\"><span class=\"stat-label\">MST OK</span>"
    @"<span class=\"stat-value green\" id=\"ms\">—</span></div>"
    @"<div class=\"stat\"><span class=\"stat-label\">MST Fail</span>"
    @"<span class=\"stat-value red\" id=\"mf\">—</span></div>"
    @"<div class=\"stat\"><span class=\"stat-label\">Sig OK</span>"
    @"<span class=\"stat-value green\" id=\"ss\">—</span></div>"
    @"<div class=\"stat\"><span class=\"stat-label\">Sig Fail</span>"
    @"<span class=\"stat-value red\" id=\"sf\">—</span></div></div>\n"
    @"<div class=\"card\"><h2>Continuity</h2>"
    @"<div class=\"stat\"><span class=\"stat-label\">Baselines</span>"
    @"<span class=\"stat-value\" id=\"cb\">—</span></div>"
    @"<div class=\"stat\"><span class=\"stat-label\">Verified</span>"
    @"<span class=\"stat-value green\" id=\"cv\">—</span></div>"
    @"<div class=\"stat\"><span class=\"stat-label\">Failures</span>"
    @"<span class=\"stat-value red\" id=\"cfail\">—</span></div>"
    @"<div class=\"stat\"><span class=\"stat-label\">Sync Resets</span>"
    @"<span class=\"stat-value\" id=\"sr\">—</span></div></div>\n"
    @"</div>\n"
    @"<div class=\"grid\">\n"
    @"<div class=\"card\" style=\"grid-column:span 2\"><h2>Upstreams</h2>"
    @"<ul class=\"upstream-list\" id=\"ul\"><li class=\"empty\">Loading…</li></ul></div>\n"
    @"<div class=\"card\"><h2>Actions</h2><div class=\"actions\">"
    @"<form class=\"input-group\" id=\"crawlForm\">"
    @"<input type=\"text\" id=\"hi\" placeholder=\"pds.example.com\" autocomplete=\"off\">"
    @"<button type=\"submit\">Request Crawl</button></form>"
    @"<div class=\"btn-row\">"
    @"<button id=\"rb\">Reconnect All</button>"
    @"<button class=\"danger\" id=\"db\">Disconnect All</button></div></div></div>\n"
    @"</div>\n"
    @"<div class=\"card\" style=\"margin-top:16px\"><h2>Live Event Feed</h2>"
    @"<div class=\"event-feed\" id=\"feed\"><div class=\"empty\">Connecting…</div></div></div>\n"
    @"<script>\n"
    @"const R=5000;let ws=null;\n"
    @"async function fj(u,o){try{const r=await fetch(u,o);return await r.json()}"
    @"catch(e){return null}}\n"
    @"function t(i,v){const e=document.getElementById(i);if(e)e.textContent=v}\n"
    @"async function ph(){const h=await fj('/api/relay/health');if(!h)return;"
    @"const d=document.getElementById('sd');"
    @"d.className='status-dot '+(h.status==='healthy'?'healthy':h.status==='degraded'?"
    @"'degraded':'down');"
    @"t('hs',h.status);t('uc',h.upstreamConnections);"
    @"t('dc',h.downstreamConnections);t('cs',h.currentSequence)}\n"
    @"async function pm(){const m=await fj('/api/relay/metrics');if(!m||!m.metrics)return;"
    @"const x=m.metrics;"
    @"t('er',x.eventsReceived);t('ev',x.eventsValidated);t('ef',x.eventsForwarded);"
    @"t('ed',x.eventsDropped);t('ms',x.mstValidationSuccess);t('mf',x.mstValidationFailure);"
    @"t('ss',x.signatureValidationSuccess);t('sf',x.signatureValidationFailure);"
    @"t('cb',x.continuityBaselines);t('cv',x.continuityVerified);"
    @"t('cfail',x.continuityFailures);t('sr',x.syncResets)}\n"
    @"async function pu(){const u=await fj('/api/relay/upstreams');if(!u||!u.upstreams)return;"
    @"const l=document.getElementById('ul');l.textContent='';"
    @"if(!u.upstreams.length){l.innerHTML='<li class=\"empty\">No upstreams configured</li>';return;}"
    @"u.upstreams.forEach(function(p){const item=document.createElement('li');"
    @"item.className='upstream-item';"
    @"const host=document.createElement('div');host.className='upstream-host';"
    @"host.textContent=p.hostname||p.url;host.title=p.url;item.appendChild(host);"
    @"const url=document.createElement('div');url.className='upstream-url';"
    @"url.textContent=p.url;url.title=p.url;item.appendChild(url);"
    @"const state=document.createElement('span');const allowed={requested:1,crawling:1,complete:1,"
    @"failed:1,'not-requested':1};const crawlState=allowed[p.crawlState]?p.crawlState:'not-requested';"
    @"state.className='badge '+crawlState;state.textContent=crawlState;item.appendChild(state);"
    @"const server=document.createElement('span');server.className='server-status';"
    @"const serverStatus={connected:1,connecting:1,disconnected:1};"
    @"const status=serverStatus[p.status]?p.status:'unknown';server.textContent=status;"
    @"item.appendChild(server);"
    @"const meta=document.createElement('span');meta.className='crawl-meta';"
    @"const repos=p.crawlRepoCount||0;const seq=p.seq||0;"
    @"meta.textContent=(p.crawlRequested?'requested · ':'')+repos+' repos · seq '+seq;"
    @"if(p.crawlError)meta.title=p.crawlError;item.appendChild(meta);l.appendChild(item)})}\n"
    @"function poll(){ph();pm();pu();"
    @"t('ts','Updated '+new Date().toLocaleTimeString())}\n"
    @"document.getElementById('crawlForm').addEventListener('submit',async function(e){"
    @"e.preventDefault();const h=document.getElementById('hi').value.trim();if(!h)return;"
    @"await fetch('/api/relay/requestCrawl',{method:'POST',"
    @"headers:{'Content-Type':'application/json'},body:JSON.stringify({hostname:h})});"
    @"document.getElementById('hi').value='';setTimeout(pu,1000)})\n"
    @"document.getElementById('rb').addEventListener('click',async function(){"
    @"await fetch('/api/relay/upstreams/reconnect-all',{method:'POST'});setTimeout(pu,1000)})\n"
    @"document.getElementById('db').addEventListener('click',async function(){"
    @"await fetch('/api/relay/upstreams/disconnect-all',{method:'POST'});setTimeout(pu,500)})\n"
    @"function cw(){const p=location.protocol==='https:'?'wss:':'ws:';"
    @"ws=new WebSocket(p+'//'+location.host+'/xrpc/com.atproto.sync.subscribeRepos');"
    @"ws.onopen=function(){document.getElementById('feed').innerHTML="
    @"'<div class=\"empty\">Listening…</div>'};"
    @"ws.onmessage=function(ev){const f=document.getElementById('feed');"
    @"if(f.querySelector('.empty'))f.innerHTML='';"
    @"let tp='unknown',dt='';try{const d=JSON.parse(ev.data);"
    @"if(Array.isArray(d)){tp=d[0]||'event';dt=JSON.stringify(d).slice(0,200)}"
    @"else{tp=d.type||d.kind||'event';dt=JSON.stringify(d).slice(0,200)}}"
    @"catch(e){tp='raw';dt=ev.data.slice(0,200)};"
    @"const tm=new Date().toLocaleTimeString();"
    @"const v=document.createElement('div');v.className='event';"
    @"const timeEl=document.createElement('span');timeEl.className='event-time';timeEl.textContent=tm;"
    @"const typeEl=document.createElement('span');typeEl.className='event-type';typeEl.textContent=tp;"
    @"const detailEl=document.createElement('span');detailEl.className='event-detail';detailEl.textContent=dt;"
    @"v.appendChild(timeEl);v.appendChild(typeEl);v.appendChild(detailEl);"
    @"f.insertBefore(v,f.firstChild);"
    @"while(f.children.length>200)f.removeChild(f.lastChild)};"
    @"ws.onerror=function(){document.getElementById('feed').innerHTML="
    @"'<div class=\"empty\">Connection error</div>'};"
    @"ws.onclose=function(){document.getElementById('feed').innerHTML="
    @"'<div class=\"empty\">Disconnected. Reconnecting…</div>'};"
    @"setTimeout(cw,3000)}\n"
    @"poll();setInterval(poll,R);cw();\n"
    @"</script>\n"
    @"</body>\n"
    @"</html>";
}
