// GENERATED CODE - DO NOT EDIT
// This file was generated by scripts/generate.ts
/* eslint-disable */
// @ts-nocheck

export interface LexiconQuery<Params = any, Input = any, Output = any> {
  params?: Params;
  input?: Input;
  output?: Output;
}

export interface LexiconProcedure<Input = any, Output = any> {
  input?: Input;
  output?: Output;
}

export interface Lexicons {
}

export const LEXICON_METHOD_TYPES = {
} as const;


export type LexiconIds = keyof Lexicons;
export type LexiconQueryIds = { [K in LexiconIds]: Lexicons[K] extends { type: "query" } ? K : never }[LexiconIds];
export type LexiconProcedureIds = { [K in LexiconIds]: Lexicons[K] extends { type: "procedure" } ? K : never }[LexiconIds];

export type QueryParams<K extends LexiconQueryIds> = Lexicons[K] extends { params: infer P } ? P : never;
export type QueryOutput<K extends LexiconQueryIds> = Lexicons[K] extends { output: infer O } ? O : never;
export type ProcedureInput<K extends LexiconProcedureIds> = Lexicons[K] extends { input: infer I } ? I : never;
export type ProcedureOutput<K extends LexiconProcedureIds> = Lexicons[K] extends { output: infer O } ? O : never;

/** Strongly typed nested API client. */
export interface GeneratedClient {
}
