import { expandGlob } from "https://deno.land/std@0.224.0/fs/expand_glob.ts";
import { join, dirname } from "https://deno.land/std@0.224.0/path/mod.ts";

const LEXICONS_DIR = join(Deno.cwd(), "../../lexicons");
const OUT_FILE = join(Deno.cwd(), "lexicons.ts");

interface LexiconDoc {
  lexicon: number;
  id: string;
  defs: Record<string, any>;
}

async function main() {
  const docs: LexiconDoc[] = [];
  for await (const file of expandGlob(join(LEXICONS_DIR, "**/*.json"))) {
    if (file.isFile) {
      const text = await Deno.readTextFile(file.path);
      try {
        docs.push(JSON.parse(text));
      } catch (e) {
        console.error(`Error parsing ${file.path}:`, e);
      }
    }
  }

  docs.sort((a, b) => a.id.localeCompare(b.id));

  let out = `// GENERATED CODE - DO NOT EDIT
// This file was generated by scripts/generate.ts
/* eslint-disable */
// @ts-nocheck

export interface LexiconQuery<Params = any, Input = any, Output = any> {
  params?: Params;
  input?: Input;
  output?: Output;
}

export interface LexiconProcedure<Input = any, Output = any> {
  input?: Input;
  output?: Output;
}

export interface Lexicons {
`;

  const validDocs = docs.filter(doc => doc.defs["main"] && (doc.defs["main"].type === "query" || doc.defs["main"].type === "procedure" || doc.defs["main"].type === "record"));

  for (const doc of validDocs) {
    const mainDef = doc.defs["main"];
    
    if (mainDef.type === "query" || mainDef.type === "procedure") {
      out += `  "${doc.id}": {\n`;
      if (mainDef.type === "query") {
        out += `    type: "query";\n`;
        // parameters
        if (mainDef.parameters && mainDef.parameters.properties) {
          out += `    params: {\n`;
          for (const [key, prop] of Object.entries(mainDef.parameters.properties)) {
            const required = mainDef.parameters.required?.includes(key) ? "" : "?";
            out += `      "${key}"${required}: ${mapType(prop as any)};\n`;
          }
          out += `    };\n`;
        } else {
          out += `    params: Record<string, never>;\n`;
        }
      } else {
        out += `    type: "procedure";\n`;
      }

      // input
      if (mainDef.input && mainDef.input.schema) {
        out += `    input: ${mapSchema(mainDef.input.schema)};\n`;
      } else {
        out += `    input: never;\n`;
      }

      // output
      if (mainDef.output && mainDef.output.schema) {
        out += `    output: ${mapSchema(mainDef.output.schema)};\n`;
      } else {
        out += `    output: never;\n`;
      }
      
      out += `  };\n`;
    } else if (mainDef.type === "record") {
      out += `  "${doc.id}": {\n`;
      out += `    type: "record";\n`;
      out += `    record: ${mapSchema(mainDef.record)};\n`;
      out += `  };\n`;
    }
  }

  out += "}\n\n";

  // Create client escape hatch types
  out += `
export type LexiconIds = keyof Lexicons;
export type LexiconQueryIds = { [K in LexiconIds]: Lexicons[K] extends { type: "query" } ? K : never }[LexiconIds];
export type LexiconProcedureIds = { [K in LexiconIds]: Lexicons[K] extends { type: "procedure" } ? K : never }[LexiconIds];

export type QueryParams<K extends LexiconQueryIds> = Lexicons[K] extends { params: infer P } ? P : never;
export type QueryOutput<K extends LexiconQueryIds> = Lexicons[K] extends { output: infer O } ? O : never;
export type ProcedureInput<K extends LexiconProcedureIds> = Lexicons[K] extends { input: infer I } ? I : never;
export type ProcedureOutput<K extends LexiconProcedureIds> = Lexicons[K] extends { output: infer O } ? O : never;

/** Strongly typed nested API client. */
export interface GeneratedClient {
`;

  // Build the tree
  const tree: any = {};
  for (const doc of validDocs) {
      if (doc.defs["main"].type === "record") continue;
      const parts = doc.id.split(".");
      let current = tree;
      for (let i = 0; i < parts.length; i++) {
          const part = parts[i];
          if (i === parts.length - 1) {
              current[part] = doc;
          } else {
              current[part] = current[part] || {};
              current = current[part];
          }
      }
  }

  function generateInterface(node: any, indent: string): string {
      let result = "";
      const entries = Object.entries(node).sort(([a], [b]) => a.localeCompare(b));
      for (const [key, value] of entries) {
          if (value.id) {
              // It's a leaf (method)
              const doc = value as LexiconDoc;
              const isQuery = doc.defs["main"].type === "query";
              if (isQuery) {
                  result += `${indent}"${key}"(params?: QueryParams<"${doc.id}">, token?: string): Promise<QueryOutput<"${doc.id}">>;\n`;
              } else {
                  result += `${indent}"${key}"(input?: ProcedureInput<"${doc.id}">, token?: string): Promise<ProcedureOutput<"${doc.id}">>;\n`;
              }
          } else {
              // It's a namespace
              result += `${indent}"${key}": {\n`;
              result += generateInterface(value, indent + "  ");
              result += `${indent}};\n`;
          }
      }
      return result;
  }

  out += generateInterface(tree, "  ");
  out += "}\n";

  await Deno.mkdir(dirname(OUT_FILE), { recursive: true });
  await Deno.writeTextFile(OUT_FILE, out);
  console.log(`Wrote ${validDocs.length} lexicons to ${OUT_FILE}`);
}

function mapType(prop: any): string {
  if (prop.type === "string") return "string";
  if (prop.type === "integer" || prop.type === "number") return "number";
  if (prop.type === "boolean") return "boolean";
  if (prop.type === "array") return `Array<${mapType(prop.items || {type: "unknown"})}>`;
  if (prop.type === "object") return "Record<string, any>";
  if (prop.type === "blob") return "any /* blob */";
  if (prop.type === "ref") return "any /* ref */";
  if (prop.type === "union") return "any /* union */";
  return "any";
}

function mapSchema(schema: any): string {
  if (!schema) return "any";
  if (schema.type === "object" && schema.properties) {
    let out = "{\n";
    for (const [key, prop] of Object.entries(schema.properties)) {
      const required = schema.required?.includes(key) ? "" : "?";
      out += `      "${key}"${required}: ${mapType(prop)};\n`;
    }
    out += "    }";
    return out;
  }
  return mapType(schema);
}

if (import.meta.main) {
  main();
}
