// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $api_auth from "./routes/api/auth.ts";
import * as $api_config from "./routes/api/config.ts";
import * as $api_debug_appview_timeline from "./routes/api/debug/appview-timeline.ts";
import * as $api_events from "./routes/api/events.ts";
import * as $api_execute from "./routes/api/execute.ts";
import * as $api_health from "./routes/api/health.ts";
import * as $api_reset from "./routes/api/reset.ts";
import * as $api_state from "./routes/api/state.ts";
import * as $api_ws from "./routes/api/ws.ts";
import * as $index from "./routes/index.tsx";
import * as $proxy_service_path_ from "./routes/proxy/[service]/[...path].ts";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/api/auth.ts": $api_auth,
    "./routes/api/config.ts": $api_config,
    "./routes/api/debug/appview-timeline.ts": $api_debug_appview_timeline,
    "./routes/api/events.ts": $api_events,
    "./routes/api/execute.ts": $api_execute,
    "./routes/api/health.ts": $api_health,
    "./routes/api/reset.ts": $api_reset,
    "./routes/api/state.ts": $api_state,
    "./routes/api/ws.ts": $api_ws,
    "./routes/index.tsx": $index,
    "./routes/proxy/[service]/[...path].ts": $proxy_service_path_,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
