// GENERATED CODE - DO NOT EDIT
// This file was generated by scripts/generate.ts
/* eslint-disable */
// @ts-nocheck

export interface LexiconQuery<Params = unknown, Input = unknown, Output = unknown> {
  inputEncoding?: string;
  outputEncoding?: string;
  params?: Params;
  input?: Input;
  output?: Output;
}

export interface LexiconProcedure<Input = unknown, Output = unknown> {
  inputEncoding?: string;
  outputEncoding?: string;
  input?: Input;
  output?: Output;
}

export type BinaryXrpcResponse = [status: number, contentType: string, data: Uint8Array];

export interface LexiconDefs {
}

export interface Lexicons {
}

export const LEXICON_METHOD_TYPES = {
} as const;

export const LEXICON_METHOD_INPUT_ENCODINGS = {
} as const;

export const LEXICON_METHOD_OUTPUT_ENCODINGS = {
} as const;


export type LexiconIds = keyof Lexicons;
export type LexiconQueryIds = { [K in LexiconIds]: Lexicons[K] extends { type: "query" } ? K : never }[LexiconIds];
export type LexiconProcedureIds = { [K in LexiconIds]: Lexicons[K] extends { type: "procedure" } ? K : never }[LexiconIds];

export type QueryParams<K extends LexiconQueryIds> = Lexicons[K] extends { params: infer P } ? P : never;
export type QueryOutput<K extends LexiconQueryIds> = Lexicons[K] extends { output: infer O } ? O : never;
export type ProcedureInput<K extends LexiconProcedureIds> = Lexicons[K] extends { input: infer I } ? I : never;
export type ProcedureOutput<K extends LexiconProcedureIds> = Lexicons[K] extends { output: infer O } ? O : never;
export type QueryOutputEncoding<K extends LexiconQueryIds> = Lexicons[K] extends { outputEncoding: infer E } ? E : never;
export type ProcedureInputEncoding<K extends LexiconProcedureIds> = Lexicons[K] extends { inputEncoding: infer E } ? E : never;
export type ProcedureOutputEncoding<K extends LexiconProcedureIds> = Lexicons[K] extends { outputEncoding: infer E } ? E : never;

export interface CallOptions {
  headers?: { Authorization?: string };
}

export interface XrpcCaller {
  call(method: string, data?: unknown, tokenOrOpts?: string | CallOptions): Promise<unknown>;
}

/** Strongly typed nested API client. */
export interface GeneratedClient {
}

export function createGeneratedClient(caller: XrpcCaller): GeneratedClient {
  return {
  };
}
