source "https://rubygems.org"

gem "jekyll", "~> 4.3.0"
gem "jekyll-theme-minimal"
gem "jekyll-sitemap"
gem "jekyll-feed"
gem "kramdown-parser-gfm"

group :jekyll_plugins do
  gem "jekyll-sitemap"
  gem "jekyll-feed"
end
