#!/bin/bash
# VitePress Documentation Build Script
# 
# This script runs validation checks and builds the VitePress documentation site.
# It ensures documentation quality before deployment.

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "======================================================================"
echo "VitePress Documentation Build Pipeline"
echo "======================================================================"
echo ""

# Change to docs directory
cd "$(dirname "$0")/.."

# Step 1: Validate links
echo "==> Step 1: Validating internal links..."
if npx tsx scripts/validate-docs.ts --check-links; then
    echo -e "${GREEN}✓ Link validation passed${NC}"
else
    echo -e "${RED}✗ Link validation failed${NC}"
    exit 1
fi
echo ""

# Step 2: Validate diagrams
echo "==> Step 2: Validating diagrams..."
if bash ../scripts/validate-doc-diagrams.sh; then
    echo -e "${GREEN}✓ Diagram validation passed${NC}"
else
    echo -e "${YELLOW}⚠ Diagram validation warnings (non-fatal)${NC}"
fi
echo ""

# Step 3: Validate code blocks
echo "==> Step 3: Validating code blocks..."
if npx tsx scripts/validate-docs.ts --check-code-blocks; then
    echo -e "${GREEN}✓ Code block validation passed${NC}"
else
    echo -e "${RED}✗ Code block validation failed${NC}"
    exit 1
fi
echo ""

# Step 4: Build VitePress site
echo "==> Step 4: Building VitePress site..."
if npm run docs:build; then
    echo -e "${GREEN}✓ VitePress build successful${NC}"
else
    echo -e "${RED}✗ VitePress build failed${NC}"
    exit 1
fi
echo ""

# Step 5: Verify build output
echo "==> Step 5: Verifying build output..."
if [ -f ".vitepress/dist/index.html" ]; then
    echo -e "${GREEN}✓ Build output verified${NC}"
else
    echo -e "${RED}✗ Build output missing${NC}"
    exit 1
fi
echo ""

# Step 6: Generate sitemap (if not already generated by VitePress)
echo "==> Step 6: Checking sitemap..."
if [ -f ".vitepress/dist/sitemap.xml" ]; then
    echo -e "${GREEN}✓ Sitemap found${NC}"
else
    echo -e "${YELLOW}⚠ Sitemap not found (may need manual generation)${NC}"
fi
echo ""

echo "======================================================================"
echo -e "${GREEN}Build pipeline completed successfully!${NC}"
echo "======================================================================"
echo ""
echo "Build output: .vitepress/dist/"
echo "To preview: npm run docs:preview"
echo ""
