import { expandGlob } from "@std/fs/expand-glob";
import { dirname, fromFileUrl, join, relative } from "@std/path";

const SCRIPT_DIR = dirname(fromFileUrl(import.meta.url));
const PACKAGE_DIR = dirname(SCRIPT_DIR);
const REPO_ROOT = dirname(dirname(PACKAGE_DIR));
const DEFAULT_LEXICONS_DIR = join(REPO_ROOT, "lexicons");
const DEFAULT_OUT_FILE = join(PACKAGE_DIR, "lexicons.ts");

interface LexiconDoc {
  lexicon: number;
  id: string;
  defs: Record<string, LexiconDef>;
}

interface LexiconDef {
  type?: string;
  parameters?: LexiconParams;
  input?: LexiconBody;
  output?: LexiconBody;
  record?: LexiconSchema;
}

interface LexiconParams {
  properties?: Record<string, LexiconSchema>;
  required?: string[];
}

interface LexiconBody {
  schema?: LexiconSchema;
}

interface LexiconSchema {
  type?: string;
  properties?: Record<string, LexiconSchema>;
  required?: string[];
  items?: LexiconSchema;
}

interface LocatedLexiconDoc {
  doc: LexiconDoc;
  path: string;
}

export interface GenerateLexiconsOptions {
  lexiconsDir?: string;
  outFile?: string;
}

export interface GenerateLexiconsResult {
  lexiconCount: number;
  outFile: string;
}

export async function generateLexicons(
  options: GenerateLexiconsOptions = {},
): Promise<GenerateLexiconsResult> {
  const lexiconsDir = options.lexiconsDir ?? DEFAULT_LEXICONS_DIR;
  const outFile = options.outFile ?? DEFAULT_OUT_FILE;
  const docs: LocatedLexiconDoc[] = [];
  for await (const file of expandGlob(join(lexiconsDir, "**/*.json"))) {
    if (file.isFile) {
      const text = await Deno.readTextFile(file.path);
      try {
        docs.push({ doc: JSON.parse(text) as LexiconDoc, path: file.path });
      } catch (e) {
        console.error(`Error parsing ${file.path}:`, e);
      }
    }
  }

  const selectedDocs = selectCanonicalDocs(docs, lexiconsDir);

  const generated = renderLexicons(selectedDocs);

  await Deno.mkdir(dirname(outFile), { recursive: true });
  await Deno.writeTextFile(outFile, generated.source);
  return { lexiconCount: generated.lexiconCount, outFile };
}

async function main() {
  const result = await generateLexicons();
  console.log(`Wrote ${result.lexiconCount} lexicons to ${result.outFile}`);
}

function selectCanonicalDocs(
  docs: LocatedLexiconDoc[],
  lexiconsDir: string,
): LexiconDoc[] {
  const byId = new Map<string, LocatedLexiconDoc[]>();
  for (const doc of docs) {
    const current = byId.get(doc.doc.id) ?? [];
    current.push(doc);
    byId.set(doc.doc.id, current);
  }

  const selected: LocatedLexiconDoc[] = [];
  const duplicateErrors: string[] = [];

  for (const [id, candidates] of byId) {
    if (candidates.length === 1) {
      selected.push(candidates[0]);
      continue;
    }

    const canonicalPath = join(lexiconsDir, ...id.split(".")) + ".json";
    const canonicalCandidates = candidates.filter((candidate) =>
      candidate.path === canonicalPath
    );
    if (canonicalCandidates.length === 1) {
      selected.push(canonicalCandidates[0]);
      continue;
    }

    const paths = candidates
      .map((candidate) => relative(lexiconsDir, candidate.path))
      .sort();
    duplicateErrors.push(
      `${id}: ${paths.join(", ")} (expected canonical path ${
        relative(lexiconsDir, canonicalPath)
      })`,
    );
  }

  if (duplicateErrors.length > 0) {
    throw new Error(
      `Duplicate lexicon ids without a unique canonical path:\n${
        duplicateErrors.sort().join("\n")
      }`,
    );
  }

  return selected.map(({ doc }) => doc);
}

function renderLexicons(docs: LexiconDoc[]): {
  source: string;
  lexiconCount: number;
} {
  docs.sort((a, b) => a.id.localeCompare(b.id));

  let out = `// GENERATED CODE - DO NOT EDIT
// This file was generated by scripts/generate.ts
/* eslint-disable */
// @ts-nocheck

export interface LexiconQuery<Params = any, Input = any, Output = any> {
  params?: Params;
  input?: Input;
  output?: Output;
}

export interface LexiconProcedure<Input = any, Output = any> {
  input?: Input;
  output?: Output;
}

export interface Lexicons {
`;

  const validDocs = docs.filter((doc) =>
    doc.defs["main"] &&
    (doc.defs["main"].type === "query" ||
      doc.defs["main"].type === "procedure" ||
      doc.defs["main"].type === "record")
  );

  for (const doc of validDocs) {
    const mainDef = doc.defs["main"];

    if (mainDef.type === "query" || mainDef.type === "procedure") {
      out += `  "${doc.id}": {\n`;
      if (mainDef.type === "query") {
        out += `    type: "query";\n`;
        // parameters
        if (mainDef.parameters && mainDef.parameters.properties) {
          out += `    params: {\n`;
          for (
            const [key, prop] of Object.entries(mainDef.parameters.properties)
          ) {
            const required = mainDef.parameters.required?.includes(key)
              ? ""
              : "?";
            out += `      "${key}"${required}: ${mapType(prop)};\n`;
          }
          out += `    };\n`;
        } else {
          out += `    params: Record<string, never>;\n`;
        }
      } else {
        out += `    type: "procedure";\n`;
      }

      // input
      if (mainDef.input && mainDef.input.schema) {
        out += `    input: ${mapSchema(mainDef.input.schema)};\n`;
      } else {
        out += `    input: never;\n`;
      }

      // output
      if (mainDef.output && mainDef.output.schema) {
        out += `    output: ${mapSchema(mainDef.output.schema)};\n`;
      } else {
        out += `    output: never;\n`;
      }

      out += `  };\n`;
    } else if (mainDef.type === "record") {
      out += `  "${doc.id}": {\n`;
      out += `    type: "record";\n`;
      out += `    record: ${mapSchema(mainDef.record)};\n`;
      out += `  };\n`;
    }
  }

  out += "}\n\n";

  out += "export const LEXICON_METHOD_TYPES = {\n";
  for (const doc of validDocs) {
    const mainDef = doc.defs["main"];
    if (mainDef.type === "query" || mainDef.type === "procedure") {
      out += `  "${doc.id}": "${mainDef.type}",\n`;
    }
  }
  out += "} as const;\n\n";

  // Create client escape hatch types
  out += `
export type LexiconIds = keyof Lexicons;
export type LexiconQueryIds = { [K in LexiconIds]: Lexicons[K] extends { type: "query" } ? K : never }[LexiconIds];
export type LexiconProcedureIds = { [K in LexiconIds]: Lexicons[K] extends { type: "procedure" } ? K : never }[LexiconIds];

export type QueryParams<K extends LexiconQueryIds> = Lexicons[K] extends { params: infer P } ? P : never;
export type QueryOutput<K extends LexiconQueryIds> = Lexicons[K] extends { output: infer O } ? O : never;
export type ProcedureInput<K extends LexiconProcedureIds> = Lexicons[K] extends { input: infer I } ? I : never;
export type ProcedureOutput<K extends LexiconProcedureIds> = Lexicons[K] extends { output: infer O } ? O : never;

/** Strongly typed nested API client. */
export interface GeneratedClient {
`;

  // Build the tree
  interface ClientTree {
    [key: string]: LexiconDoc | ClientTree;
  }
  const tree: ClientTree = {};
  for (const doc of validDocs) {
    if (doc.defs["main"].type === "record") continue;
    const parts = doc.id.split(".");
    let current = tree;
    for (let i = 0; i < parts.length; i++) {
      const part = parts[i];
      if (i === parts.length - 1) {
        current[part] = doc;
      } else {
        current[part] = current[part] || {};
        current = current[part] as ClientTree;
      }
    }
  }

  function isLexiconDoc(value: LexiconDoc | ClientTree): value is LexiconDoc {
    return "id" in value && typeof value.id === "string";
  }

  function generateInterface(node: ClientTree, indent: string): string {
    let result = "";
    const entries = Object.entries(node).sort(([a], [b]) => a.localeCompare(b));
    for (const [key, value] of entries) {
      if (isLexiconDoc(value)) {
        // It's a leaf (method)
        const doc = value;
        const isQuery = doc.defs["main"].type === "query";
        if (isQuery) {
          result +=
            `${indent}"${key}"(params?: QueryParams<"${doc.id}">, token?: string): Promise<QueryOutput<"${doc.id}">>;\n`;
        } else {
          result +=
            `${indent}"${key}"(input?: ProcedureInput<"${doc.id}">, token?: string): Promise<ProcedureOutput<"${doc.id}">>;\n`;
        }
      } else {
        // It's a namespace
        result += `${indent}"${key}": {\n`;
        result += generateInterface(value, indent + "  ");
        result += `${indent}};\n`;
      }
    }
    return result;
  }

  out += generateInterface(tree, "  ");
  out += "}\n";

  return { source: out, lexiconCount: validDocs.length };
}

function mapType(prop: LexiconSchema): string {
  if (prop.type === "string") return "string";
  if (prop.type === "integer" || prop.type === "number") return "number";
  if (prop.type === "boolean") return "boolean";
  if (prop.type === "array") {
    return `Array<${mapType(prop.items || { type: "unknown" })}>`;
  }
  if (prop.type === "object") return "Record<string, any>";
  if (prop.type === "blob") return "any /* blob */";
  if (prop.type === "ref") return "any /* ref */";
  if (prop.type === "union") return "any /* union */";
  return "any";
}

function mapSchema(schema: LexiconSchema | undefined): string {
  if (!schema) return "any";
  if (schema.type === "object" && schema.properties) {
    let out = "{\n";
    for (const [key, prop] of Object.entries(schema.properties)) {
      const required = schema.required?.includes(key) ? "" : "?";
      out += `      "${key}"${required}: ${mapType(prop)};\n`;
    }
    out += "    }";
    return out;
  }
  return mapType(schema);
}

if (import.meta.main) {
  main();
}
