// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $api_network_health from "./routes/api/network/health.ts";
import * as $api_network_index from "./routes/api/network/index.ts";
import * as $api_network_start from "./routes/api/network/start.ts";
import * as $api_network_stop from "./routes/api/network/stop.ts";
import * as $api_runs from "./routes/api/runs.ts";
import * as $api_runs_runId_ from "./routes/api/runs/[runId].ts";
import * as $api_runs_runId_logs from "./routes/api/runs/[runId]/logs.ts";
import * as $api_runs_runId_progress from "./routes/api/runs/[runId]/progress.ts";
import * as $api_scenarios from "./routes/api/scenarios.ts";
import * as $index from "./routes/index.tsx";
import * as $run_runId_ from "./routes/run/[runId].tsx";
import * as $scenario_id_ from "./routes/scenario/[id].tsx";
import * as $LogViewer from "./islands/LogViewer.tsx";
import * as $NetworkStatus from "./islands/NetworkStatus.tsx";
import * as $RunProgress from "./islands/RunProgress.tsx";
import * as $RunPoller from "./islands/RunPoller.tsx";
import * as $ScenarioRunner from "./islands/ScenarioRunner.tsx";
import * as $Sidebar from "./islands/Sidebar.tsx";
import * as $Toolbar from "./islands/Toolbar.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/api/network/health.ts": $api_network_health,
    "./routes/api/network/index.ts": $api_network_index,
    "./routes/api/network/start.ts": $api_network_start,
    "./routes/api/network/stop.ts": $api_network_stop,
    "./routes/api/runs.ts": $api_runs,
    "./routes/api/runs/[runId].ts": $api_runs_runId_,
    "./routes/api/runs/[runId]/logs.ts": $api_runs_runId_logs,
    "./routes/api/runs/[runId]/progress.ts": $api_runs_runId_progress,
    "./routes/api/scenarios.ts": $api_scenarios,
    "./routes/index.tsx": $index,
    "./routes/run/[runId].tsx": $run_runId_,
    "./routes/scenario/[id].tsx": $scenario_id_,
  },
  islands: {
    "./islands/LogViewer.tsx": $LogViewer,
    "./islands/NetworkStatus.tsx": $NetworkStatus,
    "./islands/RunProgress.tsx": $RunProgress,
    "./islands/RunPoller.tsx": $RunPoller,
    "./islands/ScenarioRunner.tsx": $ScenarioRunner,
    "./islands/Sidebar.tsx": $Sidebar,
    "./islands/Toolbar.tsx": $Toolbar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
