#!/usr/bin/env -S deno run --allow-read --allow-write

/**
 * Generates Objective-C NSID string constants from the canonical lexicon root.
 *
 * Outputs:
 *   Garazyk/Sources/Network/Generated/GZXrpcNSID.h
 *   Garazyk/Sources/Network/Generated/GZXrpcNSID.m
 *
 * Each endpoint (query, procedure, subscription) gets an NSString * const
 * in the form: kGZXrpcNSID_<nsid with dots replaced by underscores>.
 *
 * Usage: deno run -A scripts/generate_nsid_constants.ts
 */

import { expandGlob } from "@std/fs/expand-glob";
import { dirname, fromFileUrl, join } from "@std/path";

const SCRIPT_DIR = dirname(fromFileUrl(import.meta.url));
const REPO_ROOT = dirname(SCRIPT_DIR);
const LEXICONS_DIR = join(REPO_ROOT, "Garazyk", "Resources", "lexicons");
const OUT_DIR = join(REPO_ROOT, "Garazyk", "Sources", "Network", "Generated");
const HEADER_PATH = join(OUT_DIR, "GZXrpcNSID.h");
const SOURCE_PATH = join(OUT_DIR, "GZXrpcNSID.m");

interface LexiconDoc {
  lexicon: number;
  id: string;
  defs: Record<string, { type?: string }>;
}

function nsidToConstantName(nsid: string): string {
  return "kGZXrpcNSID_" + nsid.replace(/\./g, "_").replace(/-/g, "_");
}

async function main() {
  const endpointNsids: string[] = [];

  for await (const file of expandGlob(join(LEXICONS_DIR, "**/*.json"))) {
    if (!file.isFile) continue;
    let doc: LexiconDoc;
    try {
      doc = JSON.parse(await Deno.readTextFile(file.path)) as LexiconDoc;
    } catch {
      console.error(`Error parsing ${file.path}`);
      continue;
    }
    const mainDef = doc.defs?.main;
    if (!mainDef) continue;
    const type = mainDef.type;
    if (type === "query" || type === "procedure" || type === "subscription") {
      endpointNsids.push(doc.id);
    }
  }

  endpointNsids.sort();

  if (endpointNsids.length === 0) {
    console.error("No endpoint definitions found; refusing to generate empty files");
    Deno.exit(1);
  }

  await Deno.mkdir(OUT_DIR, { recursive: true });
  await Deno.writeTextFile(HEADER_PATH, renderHeader(endpointNsids));
  await Deno.writeTextFile(SOURCE_PATH, renderSource(endpointNsids));

  console.log(
    `Generated ${endpointNsids.length} NSID constants:\n  ${HEADER_PATH}\n  ${SOURCE_PATH}`,
  );
}

function renderHeader(nsids: string[]): string {
  const lines = [
    `// GENERATED CODE - DO NOT EDIT`,
    `// Generated by scripts/generate_nsid_constants.ts`,
    `// Canonical lexicon root: Garazyk/Resources/lexicons`,
    ``,
    `#import <Foundation/Foundation.h>`,
    ``,
    `NS_ASSUME_NONNULL_BEGIN`,
    ``,
    `/*!`,
    ` @file GZXrpcNSID.h`,
    ``,
    ` @abstract Generated NSID string constants for all AT Protocol XRPC endpoints.`,
    ``,
    ` @discussion Each constant is an \`NSString * const\` carrying the`,
    ` fully-qualified method NSID (e.g. \`com.atproto.server.describeServer\`).`,
    ` Prefer these over raw \`@\"...\"\` string literals in XRPC registration`,
    ` call sites.`,
    ``,
    ` A CI lint (narzedzia) forbids new raw literal registrations so drift is`,
    ` caught at review time rather than after merge.`,
    ``,
    ` @generated`,
    ` */`,
    ``,
  ];

  for (const nsid of nsids) {
    const name = nsidToConstantName(nsid);
    lines.push(`/*! NSID for ${nsid}. */`);
    lines.push(`extern NSString * const ${name};`);
    lines.push(``);
  }

  lines.push(`NS_ASSUME_NONNULL_END`);
  return lines.join("\n") + "\n";
}

function renderSource(nsids: string[]): string {
  const lines = [
    `// GENERATED CODE - DO NOT EDIT`,
    `// Generated by scripts/generate_nsid_constants.ts`,
    ``,
    `#import "Network/Generated/GZXrpcNSID.h"`,
    ``,
  ];

  for (const nsid of nsids) {
    const name = nsidToConstantName(nsid);
    lines.push(`NSString * const ${name} = @"${nsid}";`);
  }

  return lines.join("\n") + "\n";
}

if (import.meta.main) {
  await main();
}
