#!/bin/bash
# Generate XRPC corpus files for fuzzing

CORPUS_DIR="fuzzing/corpus/xrpc"
mkdir -p "$CORPUS_DIR"

echo '{ "identifier": "test handle.bsky.social", "password": "test-password-123" }' > "$CORPUS_DIR/createSession.json"
echo '{ "did": "did:plc:abc123" }' > "$CORPUS_DIR/refreshSession.json"
echo '{ "did": "did:plc:abc123" }' > "$CORPUS_DIR/deleteSession.json"
echo '{ "handle": "new-user.bsky.social", "email": "user@example.com", "password": "secure-pass" }' > "$CORPUS_DIR/createAccount.json"
echo '{ "handle": "user.bsky.social" }' > "$CORPUS_DIR/resolveHandle.json"
echo '{ "handle": "user.bsky.social" }' > "$CORPUS_DIR/resolveByHandle.json"
echo '{ "handle": "new-handle.bsky.social" }' > "$CORPUS_DIR/updateHandle.json"
echo '{ "repo": "did:plc:abc123", "collection": "app.bsky.feed.post", "rkey": "3k5c2l242v2c2" }' > "$CORPUS_DIR/getRecord.json"
echo '{ "repo": "did:plc:abc123", "collection": "app.bsky.feed.post", "limit": 50 }' > "$CORPUS_DIR/listRecords.json"
echo '{ "repo": "did:plc:abc123", "collection": "app.bsky.feed.post", "rkey": "3k5c2l242v2c2", "record": { "$type": "app.bsky.feed.post", "text": "test" } }' > "$CORPUS_DIR/putRecord.json"
echo '{ "repo": "did:plc:abc123", "collection": "app.bsky.feed.post", "rkey": "3k5c2l242v2c2" }' > "$CORPUS_DIR/deleteRecord.json"
echo '{ "actor": "did:plc:abc123" }' > "$CORPUS_DIR/getProfile.json"
echo '{ "actors": ["did:plc:abc123", "did:plc:def456"] }' > "$CORPUS_DIR/getProfiles.json"
echo '{ "actor": "did:plc:abc123", "limit": 50 }' > "$CORPUS_DIR/getFollows.json"
echo '{ "actor": "did:plc:abc123", "limit": 50 }' > "$CORPUS_DIR/getFollowers.json"
echo '{ "repo": "did:plc:abc123", "collection": "app.bsky.graph.follow", "rkey": "3k5c2l242v2c2", "record": { "$type": "app.bsky.graph.follow", "subject": "did:plc:target456" } }' > "$CORPUS_DIR/createFollow.json"
echo '{ "repo": "did:plc:abc123", "collection": "app.bsky.graph.block", "rkey": "3k5c2l242v2c2", "record": { "$type": "app.bsky.graph.block", "subject": "did:plc:target456" } }' > "$CORPUS_DIR/createBlock.json"
echo '{ "repo": "did:plc:abc123", "collection": "app.bsky.graph.list", "rkey": "3k5c2l242v2c2", "record": { "$type": "app.bsky.graph.list", "name": "test-list" } }' > "$CORPUS_DIR/createList.json"
echo '{ "repo": "did:plc:abc123", "collection": "app.bsky.feed.post", "rkey": "3k5c2l242v2c2", "record": { "$type": "app.bsky.feed.post", "text": "test" } }' > "$CORPUS_DIR/createPost.json"
echo '{ "repo": "did:plc:abc123", "collection": "app.bsky.feed.repost", "rkey": "3k5c2l242v2c2", "record": { "$type": "app.bsky.feed.repost", "subject": "did:x" } }' > "$CORPUS_DIR/createRepost.json"
echo '{ "repo": "did:plc:abc123", "collection": "app.bsky.feed.like", "rkey": "3k5c2l242v2c2", "record": { "$type": "app.bsky.feed.like", "subject": "did:x" } }' > "$CORPUS_DIR/createLike.json"
echo '{ "limit": 50 }' > "$CORPUS_DIR/getTimeline.json"
echo '{ "uris": ["did:plc:abc123/app.bsky.feed.post/x", "did:plc:def456/app.bsky.feed.post/y"] }' > "$CORPUS_DIR/getPosts.json"
echo '{ "uri": "did:plc:abc123/app.bsky.feed.post/x", "depth": 5 }' > "$CORPUS_DIR/getPostThread.json"
echo '{ "did": "did:plc:abc123" }' > "$CORPUS_DIR/getHead.json"
echo '{ "hostname": "pds.example.com" }' > "$CORPUS_DIR/requestCrawl.json"
echo '{ "did": "did:plc:abc123", "since": "2024-01-01T00:00:00Z", "limit": 50 }' > "$CORPUS_DIR/listBlobs.json"
echo '{}' > "$CORPUS_DIR/empty.json"
echo '{ "limit": 1 }' > "$CORPUS_DIR/minLimit.json"

echo "Generated $(ls "$CORPUS_DIR" | wc -l) XRPC corpus files"