#!/usr/bin/env -S deno run --allow-read --allow-write --allow-env

/**
 * Code generation script for the @garazyk/gruszka package.
 *
 * Reads AT Protocol lexicon JSON definitions from `Garazyk/Resources/lexicons/`
 * and writes a populated `packages/gruszka/lexicons.ts`.
 *
 * Usage:
 *   deno run --allow-read --allow-write --allow-env scripts/generate.ts
 */

import { walk } from "jsr:@std/fs@1/walk";
import { relative, resolve } from "jsr:@std/path@1";

// ── Configuration ───────────────────────────────────────────────────────────

const LEXICONS_DIR = resolve(import.meta.dirname ?? ".", "..", "Garazyk/Resources/lexicons");
const OUTPUT_FILE = resolve(import.meta.dirname ?? ".", "..", "packages/gruszka/lexicons.ts");

// ── Lexicon JSON shapes ─────────────────────────────────────────────────────

interface LexiconParams {
  type: "params";
  required?: string[];
  properties?: Record<string, unknown>;
}

interface LexiconIO {
  encoding?: string;
  schema?: unknown;
}

interface LexiconMain {
  type: "query" | "procedure" | "record" | "subscription" | "token";
  description?: string;
  parameters?: LexiconParams;
  input?: LexiconIO;
  output?: LexiconIO;
}

interface LexiconJSON {
  lexicon: number;
  id: string;
  defs: {
    main: LexiconMain;
    [key: string]: LexiconMain | undefined;
  };
}

// ── Parsed output ────────────────────────────────────────────────────────────

interface ParsedLexicon {
  id: string;
  type: "query" | "procedure";
  inputEncoding: string | undefined;
  outputEncoding: string | undefined;
}

// ── Main ────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  console.error("Scanning lexicon directory:", LEXICONS_DIR);

  const parsed: ParsedLexicon[] = [];

  for await (const entry of walk(LEXICONS_DIR, { exts: [".json"] })) {
    if (!entry.isFile) continue;

    const relPath = relative(LEXICONS_DIR, entry.path);
    try {
      const raw = await Deno.readTextFile(entry.path);
      const json: LexiconJSON = JSON.parse(raw);

      if (!json.id || !json.defs?.main) {
        console.error(`  ⚠ Skipping ${relPath}: missing id or main def`);
        continue;
      }

      const main = json.defs.main;

      // Only generate entries for query and procedure methods (not records, subscriptions, or tokens)
      if (main.type !== "query" && main.type !== "procedure") continue;

      parsed.push({
        id: json.id,
        type: main.type,
        inputEncoding: main.input?.encoding,
        outputEncoding: main.output?.encoding,
      });
    } catch (err) {
      console.error(`  ✗ Failed to parse ${relPath}: ${String(err)}`);
    }
  }

  // Sort for deterministic output
  parsed.sort((a, b) => a.id.localeCompare(b.id));

  console.error(`Found ${parsed.length} query/procedure lexicons.`);

  const output = generateOutput(parsed);
  await Deno.writeTextFile(OUTPUT_FILE, output);

  console.error(`Wrote ${OUTPUT_FILE}`);
}

// ── Code generation ─────────────────────────────────────────────────────────

function generateOutput(lexicons: ParsedLexicon[]): string {
  const header = generateHeader();
  const typeInterfaces = generateTypeInterfaces();
  const lexiconsInterface = generateLexiconsInterface(lexicons);
  const methodTypes = generateMethodTypes(lexicons);
  const inputEncodings = generateInputEncodings(lexicons);
  const outputEncodings = generateOutputEncodings(lexicons);
  const typeAliases = generateTypeAliases();
  const generatedClient = generateGeneratedClientInterface(lexicons);
  const createGeneratedClientFn = generateCreateGeneratedClient(lexicons);
  const footer = generateFooter();

  return [
    header,
    typeInterfaces,
    lexiconsInterface,
    methodTypes,
    inputEncodings,
    outputEncodings,
    typeAliases,
    generatedClient,
    createGeneratedClientFn,
    footer,
  ].join("\n");
}

function generateHeader(): string {
  return `// GENERATED CODE - DO NOT EDIT
// This file was generated by scripts/generate.ts
/* eslint-disable */
// @ts-nocheck`;
}

function generateTypeInterfaces(): string {
  return `
export interface LexiconQuery<Params = unknown, Input = unknown, Output = unknown> {
  inputEncoding?: string;
  outputEncoding?: string;
  params?: Params;
  input?: Input;
  output?: Output;
}

export interface LexiconProcedure<Input = unknown, Output = unknown> {
  inputEncoding?: string;
  outputEncoding?: string;
  input?: Input;
  output?: Output;
}

export type BinaryXrpcResponse = [status: number, contentType: string, data: Uint8Array];

/** Type definitions for lexicon schema records (populated at generation time). */
export interface LexiconDefs {
}`;
}

function generateLexiconsInterface(lexicons: ParsedLexicon[]): string {
  const lines: string[] = ["", "/** Populated AT Protocol lexicon method definitions. */", "export interface Lexicons {"];

  for (const l of lexicons) {
    if (l.type === "query") {
      lines.push(`  "${l.id}": LexiconQuery<unknown, unknown, unknown>;`);
    } else {
      lines.push(`  "${l.id}": LexiconProcedure<unknown, unknown>;`);
    }
  }

  lines.push("}");
  return lines.join("\n");
}

function generateMethodTypes(lexicons: ParsedLexicon[]): string {
  const lines: string[] = ["", "export const LEXICON_METHOD_TYPES = {"];

  for (const l of lexicons) {
    lines.push(`  "${l.id}": "${l.type}",`);
  }

  lines.push("} as const;");
  return lines.join("\n");
}

function generateInputEncodings(lexicons: ParsedLexicon[]): string {
  const lines: string[] = ["", "export const LEXICON_METHOD_INPUT_ENCODINGS = {"];

  for (const l of lexicons) {
    if (l.inputEncoding) {
      lines.push(`  "${l.id}": "${l.inputEncoding}",`);
    }
  }

  lines.push("} as const;");
  return lines.join("\n");
}

function generateOutputEncodings(lexicons: ParsedLexicon[]): string {
  const lines: string[] = ["", "export const LEXICON_METHOD_OUTPUT_ENCODINGS = {"];

  for (const l of lexicons) {
    if (l.outputEncoding) {
      lines.push(`  "${l.id}": "${l.outputEncoding}",`);
    }
  }

  lines.push("} as const;");
  return lines.join("\n");
}

function generateTypeAliases(): string {
  return `
/** Allow any procedure or query name (widened from \`keyof Lexicons\` to \`string\`
 *  so that code consuming the generated types compiles even when the
 *  \`Lexicons\` map has not been fully populated yet). */
export type LexiconIds = string;

/** Query method names. Resolves to \`never\` when the Lexicons map is empty;
 *  widened to \`string\` so that consumers with placeholder endpoints compile. */
export type LexiconQueryIds = string;

/** Procedure method names. Resolves to \`never\` when the Lexicons map is empty;
 *  widened to \`string\` so that consumers with placeholder endpoints compile. */
export type LexiconProcedureIds = string;

export type QueryParams<K extends string> =
  K extends keyof Lexicons
    ? Lexicons[K] extends { params: infer P } ? P : unknown
    : unknown;

export type QueryOutput<K extends string> =
  K extends keyof Lexicons
    ? Lexicons[K] extends { output: infer O } ? O : unknown
    : unknown;

export type ProcedureInput<K extends string> =
  K extends keyof Lexicons
    ? Lexicons[K] extends { input: infer I } ? I : unknown
    : unknown;

export type ProcedureOutput<K extends string> =
  K extends keyof Lexicons
    ? Lexicons[K] extends { output: infer O } ? O : unknown
    : unknown;

export type QueryOutputEncoding<K extends string> =
  K extends keyof Lexicons
    ? Lexicons[K] extends { outputEncoding: infer E } ? E : unknown
    : unknown;

export type ProcedureInputEncoding<K extends string> =
  K extends keyof Lexicons
    ? Lexicons[K] extends { inputEncoding: infer E } ? E : unknown
    : unknown;

export type ProcedureOutputEncoding<K extends string> =
  K extends keyof Lexicons
    ? Lexicons[K] extends { outputEncoding: infer E } ? E : unknown
    : unknown;

export interface CallOptions {
  headers?: { Authorization?: string };
}

export interface XrpcCaller {
  call(method: string, data?: unknown, tokenOrOpts?: string | CallOptions): Promise<unknown>;
}`;
}

function generateGeneratedClientInterface(_lexicons: ParsedLexicon[]): string {
  return `
/** Strongly typed nested API client. Methods are resolved dynamically
 *  via a JavaScript Proxy at runtime, so this interface only needs the
 *  index signature for TypeScript to accept arbitrary namespace chains. */
export interface GeneratedClient {
  /** Allow dynamic namespace access for methods not yet in generated map. */
  [method: string]: any;
}`;
}

function generateCreateGeneratedClient(_lexicons: ParsedLexicon[]): string {
  return `
/** Create a dynamically-dispatched nested client that routes property
 *  chains to XRPC method calls.
 *
 *  Usage:
 *    const client = createGeneratedClient(caller);
 *    await client.com.atproto.server.createAccount({ handle: "alice" });
 *    await client.app.bsky.actor.getProfile({ actor: "alice.test" });
 */
export function createGeneratedClient(caller: XrpcCaller): GeneratedClient {
  function buildProxy(path: string[]): any {
    const nsid = path.join(".");

    const target = function (...args: unknown[]): Promise<unknown> {
      if (!nsid) throw new TypeError("GeneratedClient root cannot be called directly; use namespace chains like client.com.atproto...");
      return caller.call(nsid, args[0], args[1] as string | CallOptions | undefined);
    };

    return new Proxy(target, {
      get(_t, prop: string | symbol) {
        // Handle special properties that shouldn't trigger proxy chaining
        if (typeof prop === "symbol") return undefined;
        if (prop === "then") return undefined;
        if (prop === "toJSON") return () => nsid;
        if (prop === "toString") return () => \`[GeneratedClient \${nsid || "root"}]\`;

        return buildProxy([...path, prop]);
      },
      has(_t, prop: string | symbol) {
        if (typeof prop === "symbol") return false;
        // Always report as having the property so TypeScript doesn't complain
        return true;
      },
    });
  }

  return buildProxy([]) as unknown as GeneratedClient;
}`;
}

function generateFooter(): string {
  return "";
}

// ── Run ─────────────────────────────────────────────────────────────────────

if (import.meta.main) {
  main().catch((err) => {
    console.error("Generation failed:", err);
    Deno.exit(1);
  });
}
