#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="${SCRIPT_DIR}/../.."
BUILD_DIR="${PROJECT_DIR}/build"

BINARY_NAME="kaszlak"
BINARY_PATH="${BUILD_DIR}/bin/${BINARY_NAME}"
INSTALL_PREFIX="${INSTALL_PREFIX:-/usr/local}"
DATA_DIR="${DATA_DIR:-/var/db/kaszlak}"
CONFIG_DIR="${CONFIG_DIR:-/usr/local/etc/kaszlak}"
LOG_DIR="${LOG_DIR:-/var/db/kaszlak/log}"

SYSTEM_USER="_pds"
SYSTEM_GROUP="_pds"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This operation requires root privileges."
        log_info "Run with sudo: sudo $0 $@"
        exit 1
    fi
}

check_dependencies() {
    log_info "Checking dependencies..."

    if [[ ! -f "${BINARY_PATH}" ]]; then
        log_error "Binary not found at ${BINARY_PATH}"
        log_info "Please build first: cd ${PROJECT_DIR} && cmake --build build --target kaszlak"
        exit 1
    fi

    if ! command -v launchctl &> /dev/null; then
        log_error "launchctl not found. This script requires macOS."
        exit 1
    fi

    log_info "Dependencies OK"
}

create_system_user() {
    log_info "Creating system user '${SYSTEM_USER}'..."

    if id "${SYSTEM_USER}" &> /dev/null; then
        log_info "User '${SYSTEM_USER}' already exists"
    else
        dscl . -create "/Users/${SYSTEM_USER}" UserShell "/usr/bin/false"
        dscl . -create "/Users/${SYSTEM_USER}" RealName "ATProto PDS Service"
        dscl . -create "/Users/${SYSTEM_USER}" UniqueID "505"
        dscl . -create "/Users/${SYSTEM_USER}" PrimaryGroupID "505"

        dscl . -create "/Groups/${SYSTEM_GROUP}" RealName "ATProto PDS Service"
        dscl . -create "/Groups/${SYSTEM_GROUP}" GroupMembers ""
        dscl . -create "/Groups/${SYSTEM_GROUP}" PrimaryGroupID "505"
        dscl . -create "/Groups/${SYSTEM_GROUP}" GroupMembership ""

        log_info "Created user '${SYSTEM_USER}' (UID 505)"
    fi
}

create_directories() {
    log_info "Creating directories..."

    mkdir -p "${DATA_DIR}"
    mkdir -p "${LOG_DIR}"
    mkdir -p "${CONFIG_DIR}"
    mkdir -p "${INSTALL_PREFIX}/bin"
    mkdir -p "${INSTALL_PREFIX}/etc/kaszlak"

    chown -R "${SYSTEM_USER}:${SYSTEM_GROUP}" "${DATA_DIR}"
    chown -R "${SYSTEM_USER}:${SYSTEM_GROUP}" "${LOG_DIR}"
    chown -R "${SYSTEM_USER}:${SYSTEM_GROUP}" "${CONFIG_DIR}"

    log_info "Directories created"
}

install_binary() {
    log_info "Installing binary to ${INSTALL_PREFIX}/bin/${BINARY_NAME}..."

    cp "${BINARY_PATH}" "${INSTALL_PREFIX}/bin/${BINARY_NAME}"
    chmod 755 "${INSTALL_PREFIX}/bin/${BINARY_NAME}"
    chown root:wheel "${INSTALL_PREFIX}/bin/${BINARY_NAME}"

    log_info "Binary installed"
}

install_config() {
    log_info "Installing default configuration..."

    if [[ ! -f "${CONFIG_DIR}/config.yaml" ]]; then
        cat > "${CONFIG_DIR}/config.yaml" << 'EOF'
# ATProto PDS Configuration
# Generated by install.sh

server:
  host: "0.0.0.0"
  port: 2583
  dataDirectory: "/var/db/kaszlak"

database:
  type: "sqlite"
  path: "/var/db/kaszlak/actorstore.db"

logging:
  level: "info"
  format: "json"
  path: "/var/db/kaszlak/log/server.log"

# Optional: Enable/disable features
features:
  plcDirectory: true
  didWeb: true
  inviteCodes: true

# Security settings
security:
  # Set a strong admin password after installation
  adminPassword: "change-me-in-config"
EOF
        chown "${SYSTEM_USER}:${SYSTEM_GROUP}" "${CONFIG_DIR}/config.yaml"
        chmod 640 "${CONFIG_DIR}/config.yaml"
        log_info "Default configuration installed"
    else
        log_info "Configuration already exists, skipping"
    fi
}

install_launchd() {
    log_info "Installing launchd configuration..."

    local plist_source="${PROJECT_DIR}/ATProtoPDS/Resources/LaunchDaemons/com.atproto.pds.plist"
    local plist_dest="/Library/LaunchDaemons/com.atproto.pds.plist"

    if [[ ! -f "${plist_source}" ]]; then
        log_error "LaunchDaemon plist not found at ${plist_source}"
        return 1
    fi

    sed "s|/usr/local/bin/kaszlak|${INSTALL_PREFIX}/bin/kaszlak|g" "${plist_source}" > "${plist_dest}.tmp"
    sed -i '' "s|/usr/local/etc/kaszlak/config.yaml|${CONFIG_DIR}/config.yaml|g" "${plist_dest}.tmp"
    sed -i '' "s|/var/db/kaszlak|${DATA_DIR}|g" "${plist_dest}.tmp"
    mv "${plist_dest}.tmp" "${plist_dest}"

    chown root:wheel "${plist_dest}"
    chmod 644 "${plist_dest}"

    if [[ "${SKIP_LOAD:-false}" != "true" ]]; then
        log_info "Loading LaunchDaemon..."
        launchctl unload "${plist_dest}" 2>/dev/null || true
        launchctl load "${plist_dest}"
        launchctl start com.atproto.pds
        log_info "LaunchDaemon loaded and started"
    else
        log_info "Skipped loading (use 'launchctl load ${plist_dest}' to load manually)"
    fi
}

print_summary() {
    echo ""
    echo "============================================"
    echo -e "${GREEN}Installation Complete${NC}"
    echo "============================================"
    echo ""
    echo "Binary installed: ${INSTALL_PREFIX}/bin/${BINARY_NAME}"
    echo "Configuration:    ${CONFIG_DIR}/config.yaml"
    echo "Data directory:   ${DATA_DIR}"
    echo "Log directory:    ${LOG_DIR}"
    echo ""
    echo "Commands:"
    echo "  Start server:   sudo launchctl start com.atproto.pds"
    echo "  Stop server:    sudo launchctl stop com.atproto.pds"
    echo "  View logs:      tail -f ${LOG_DIR}/daemon.log"
    echo "  Reload config:  sudo launchctl unload /Library/LaunchDaemons/com.atproto.pds.plist && sudo launchctl load /Library/LaunchDaemons/com.atproto.pds.plist"
    echo ""
    echo "Important:"
    echo "  - Edit ${CONFIG_DIR}/config.yaml} to set admin password"
    echo "  - The server runs as user '${SYSTEM_USER}' for security"
    echo "============================================"
}

usage() {
    cat << EOF
Usage: $0 [OPTIONS]

Install ATProto PDS as a system service on macOS.

OPTIONS:
    --prefix PATH      Installation prefix (default: /usr/local)
    --data-dir PATH    Data directory (default: /var/db/kaszlak)
    --config-dir PATH  Configuration directory (default: /usr/local/etc/kaszlak)
    --skip-load        Don't load launchd configuration
    --force            Overwrite existing files
    --help             Show this help

EXAMPLES:
    $0                          # Default installation
    sudo $0                     # With root privileges
    $0 --prefix /opt/kaszlak  # Custom installation path
    $0 --skip-load              # Install but don't start

EOF
    exit 0
}

main() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            --prefix)
                INSTALL_PREFIX="$2"
                shift 2
                ;;
            --data-dir)
                DATA_DIR="$2"
                shift 2
                ;;
            --config-dir)
                CONFIG_DIR="$2"
                shift 2
                ;;
            --skip-load)
                SKIP_LOAD="true"
                shift
                ;;
            --force)
                FORCE="true"
                shift
                ;;
            --help)
                usage
                ;;
            *)
                log_error "Unknown option: $1"
                usage
                ;;
        esac
    done

    echo "ATProto PDS Installer"
    echo "====================="

    check_dependencies
    check_root
    create_system_user
    create_directories
    install_binary
    install_config
    install_launchd
    print_summary
}

main "$@"
