// SPDX-FileCopyrightText: 2025-2026 Jack Valinsky
// SPDX-License-Identifier: Unlicense OR CC0-1.0
/*!
 @file PDSNonceManager.h

 @abstract Manages creation and validation of DPoP nonces.

 @discussion
    Provides cryptographically secure nonce generation and validation for
    DPoP (Demonstrating Proof-of-Possession) nonce flows. Nonces are used
    to prevent replay attacks in OAuth 2.0 token requests.

 @copyright Copyright (c) 2025-2026 Jack Valinsky
 */

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

/*!
 @class PDSNonceManager

 @abstract Manages creation and validation of DPoP nonces.

 @discussion
    Generates and validates nonces for DPoP nonce flows. Nonces are
    cryptographically random strings with a configurable expiration time.

    Thread Safety: This class is thread-safe. The shared instance may be
    accessed from any thread.

 @code
    NSString *nonce = [[PDSNonceManager sharedManager] generateNonce];
    // ... client provides nonce in DPoP proof ...
    if ([[PDSNonceManager sharedManager] validateNonce:nonce]) {
        // proceed with token issuance
    }
 @endcode
 */
@interface PDSNonceManager : NSObject

/*!
 @method sharedManager

 @abstract Returns the shared nonce manager instance.

 @return The singleton PDSNonceManager instance.
 */
+ (instancetype)sharedManager;

/*!
 @method generateNonce

 @abstract Generates a new cryptographically secure nonce.

 @return A new 32-character base64url-encoded nonce string.

 @discussion
    The nonce is generated using SecRandomCopyBytes on macOS/iOS or
    getrandom() on Linux. Nonces expire after a configurable TTL
    (default 5 minutes).
 */
- (NSString *)generateNonce;

/*!
 @method validateNonce:

 @abstract Validates a nonce provided by a client.

 @param nonce The nonce string to validate.
 @return YES if the nonce is valid and has not expired, NO otherwise.

 @discussion
    A nonce is valid if:
    - It was generated by this manager
    - It has not expired (within TTL)
    - It has not been used before (one-time use)

    After validation, the nonce is marked as used and cannot be reused.
 */
- (BOOL)validateNonce:(NSString *)nonce;

@end

NS_ASSUME_NONNULL_END
